export const playerTypes = [{
    class: 'Survivor',
    title: 'Onchain Survivor',
    description:'The jack of all trades (lol), adaptable and versatile with a balanced set of abilities that covers a wide range of effects.',
    thumbnail: 'Media/Classes/Onchain Survivor/MSURVIVOR.png',
    abilities:[],
},{
    class: 'Survivor',
    title: 'Onchain Survivor',
    description: 'The jill of all trades (lol), adaptable and versatile with a balanced set of abilities that covers a wide range of effects.',
    thumbnail: 'Media/Classes/Onchain Survivor/FSURVIVOR.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Miner',
    description: 'Strong, durable, reliable, albeit somewhat slow, have higher chance of taking good rewards.',
    thumbnail: 'Media/Classes/Miner/MMINER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Miner',
    description: 'Has a longer and battle tested proven record of protecting and surviving in the chain.',
    thumbnail: 'Media/Classes/Miner/FMINER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Staker',
    description: 'Balanced in speed and strength, stakers gain bonuses for maintaining stability and have unique defensive abilities.',
    thumbnail: 'Media/Classes/Staker/MSTAKER.png',
    abilities: [],  
},{
    class: 'Survivor',
    title: 'Staker',
    description: 'Balanced in speed and strength, stakers gain bonuses for maintaining stability and have unique defensive abilities.',
    thumbnail: 'Media/Classes/Staker/FSTAKER.png',
    abilities: [], 
},{
    class: 'Survivor',
    title: 'Developer',
    description: 'Versatile and strategic, developers can modify the environment and create powerful code-based attacks.',
    thumbnail: 'Media/Classes/Developer/MDEVELOPER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Developer',
    description: 'Versatile and strategic, developers can modify the environment and create powerful code-based attacks.',
    thumbnail: 'Media/Classes/Developer/FDEVELOPER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Trader',
    description: 'Fast and agile, traders can move quickly around the arena but have lower health. They have unique abilities related to market dynamics.',
    thumbnail: 'Media/Classes/Trader/MTRADER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Trader',
    description: 'Fast and agile, traders can move quickly around the arena but have lower health. They have unique abilities related to market dynamics.',
    thumbnail: 'Media/Classes/Trader/FTRADER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Regulator',
    description: 'Controllers of chaos, regulators can impose rules and restrictions on enemies, making them powerful crowd-control specialists.',
    thumbnail: 'Media/Classes/Regulator/MREGULATOR.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Regulator',
    description: 'Controllers of chaos, regulators can impose rules and restrictions on enemies, making them powerful crowd-control specialists.',
    thumbnail: 'Media/Classes/Regulator/FREGULATOR.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Quantum Cryptographer',
    description: 'Masters of quantum cryptography, withouth them the blockchain has no means of suriving in the future.',
    thumbnail: 'Media/Classes/Quantum/MQUANTUM.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Quantum Cryptographer',
    description: 'Masters of quantum cryptography, withouth them the blockchain has no means of suriving in the future.',
    thumbnail: 'Media/Classes/Quantum/FQUANTUM.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Crypto Botter',
    description: 'Utilizes bots and scripts for every action, very resourceful, always has an edge agaisnt other survivors.',
    thumbnail: 'Media/Classes/Crypto Botter/MBOTTER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Crypto Botter',
    description: 'Utilizes bots and scripts for every action, very resourceful, always has an edge agaisnt other survivors.',
    thumbnail: 'Media/Classes/Crypto Botter/FBOTTER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Fudder',
    description: 'Always bearish, spreading fear, uncertainty, and doubt (FUD). Fudders are unafected by the always improving  blockchain tech...',
    thumbnail: 'Media/Classes/Fudder/MFUDDER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Fudder',
    description: 'Always bearish, spreading fear, uncertainty, and doubt (FUD). Fudders are unafected by the always improving  blockchain tech...',
    thumbnail: 'Media/Classes/Fudder/FFUDDER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Crypto Astrologer',
    description: 'Uses the moon cycles and the stars and signs to predict market movements, providing unique takes based on astrological insights',
    thumbnail: 'Media/Classes/Astrologer/MASTROLOGER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Crypto Astrologer',
    description: 'Uses the moon cycles and the stars and signs to predict market movements, providing unique takes based on astrological insights',
    thumbnail: 'Media/Classes/Astrologer/FASTROLOGER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Influencer',
    description: 'Influencers have a huge following and can move markets with a single well timed post online. Tends to lean the vain side.',
    thumbnail: 'Media/Classes/Influencer/MINFLUENCER.jpg',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Influencer',
    description: 'Influencers have the ability to stand out in a crowded digital space. She has built her reputation from scratch',
    thumbnail: 'Media/Classes/Influencer/FINFLUENCER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Cabal Insider',
    description: 'Part of the inner group that manipulates markets for their benefit. They are in control.',
    thumbnail: 'Media/Classes/Insider Cabal/MCABAL.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Cabal Insider',
    description: 'Part of the inner group that manipulates markets for their benefit. They are in control.',
    thumbnail: 'Media/Classes/Insider Cabal/FCABAL.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Bitcoin MAXI',
    description: 'Holds 100% of their net worth in a Bitcoin, Never selling, always holding.  Showcases unwavering faith.',
    thumbnail: 'Media/Classes/Maxi/MMAXI.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Bitcoin MAXI',
    description: 'Holds 100% of their net worth in a Bitcoin, Never selling, always holding.  Showcases unwavering faith.',
    thumbnail: 'Media/Classes/Maxi/FMAXI.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Gambler',
    description: 'Former poker player and sports bettor turned crypto enthusiast, thriving on risk.',
    thumbnail: 'Media/Classes/Gambler/MGAMBLER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Gambler',
    description: 'Former poker player and sports bettor turned crypto enthusiast, thriving on risk.',
    thumbnail: 'Media/Classes/Gambler/FGAMBLER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Liquidator',
    description: 'Specializes in liquidating loans and protocols, causing financial chaos.',
    thumbnail: 'Media/Classes/Liquidator/MLIQUIDATOR.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Liquidator',
    description: 'Specializes in liquidating loans and protocols, causing financial chaos.',
    thumbnail: 'Media/Classes/Liquidator/FLIQUIDATOR.png',
    abilities: [], 
},{
    class: 'Survivor',
    title: 'Nocoiner',
    description: 'Does not hold  any crypto currencies,  but spends all their time discussing crypto, spreading skepticism.',

    thumbnail: 'Media/Classes/Nocoiner/MNOCOINER.png',
    abilities: [],

},{
    class: 'Survivor',
    title: 'Nocoiner',
    description: 'Does not hold  any crypto currencies,  but spends all their time discussing crypto, spreading skepticism.',

    thumbnail: 'Media/Classes/Nocoiner/FNOCOINER.png',
    abilities: [],

},{
    class: 'Survivor',
    title: 'Auditor',
    description: 'Revises code to ensure it does not contain fatal bugs, preventing exploits',

    thumbnail: 'Media/Classes/Auditor/MAUDITOR.png',
    abilities: [],

},{
    class: 'Survivor',
    title: 'Auditor',
    description: 'Revises code to ensure it does not contain fatal bugs, preventing exploits',

    thumbnail: 'Media/Classes/Auditor/FAUDITOR.png',
    abilities: [],

},{
    class: 'Survivor',
    title: 'Sleuth',
    description: 'Tracks on-chain history to uncover events and catch criminals.',
    thumbnail: 'Media/Classes/Sleuth/MSLEUTH.png',
    abilities: [], 
},{
    class: 'Survivor',
    title: 'Sleuth',
    description: 'Tracks on-chain history to uncover events and catch criminals.',
    thumbnail: 'Media/Classes/Sleuth/FSLEUTH.png',
    abilities: [], 
},{
    class: 'Survivor',
    title: 'Beta Tester',
    description: 'Tests blockchain projects during beta, discovering strengths and weaknesses',
    thumbnail: 'Media/Classes/Beta Tester/MBETATESTER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Beta Tester',
    description: 'Tests blockchain projects during beta, discovering strengths and weaknesses',
    thumbnail: 'Media/Classes/Beta Tester/FBETATESTER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Defi Expert',
    description: 'Experts in utilizing decentralized finance protocols to gain advantages.',
    thumbnail: 'Media/Classes/Defi/MDEFI.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Defi Expert',
    description: 'Experts in utilizing decentralized finance protocols to gain advantages.',
    thumbnail: 'Media/Classes/Defi/FDEFI.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Defi Hacker',
    description: 'Skilled in infiltration and sabotage, drains protocols, exploiting vulnerabilities for personal gain',
    thumbnail: 'Media/Classes/Defi Hacker/MDEFIHACKER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Defi Hacker',
    description: 'Skilled in infiltration and sabotage, drains protocols, exploiting vulnerabilities for personal gain',
    thumbnail: 'Media/Classes/Defi Hacker/FDEFIHACKER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Sybiller',
    description: 'Uses multiple fake personas to forge voting results, airdrops, and more.',
    thumbnail: 'Media/Classes/Sybiller/MSYBILLER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Sybiller',
    description: 'Uses multiple fake personas to forge voting results, airdrops, and more.',
    thumbnail: 'Media/Classes/Sybiller/FSYBILLER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Validator',
    description: 'Ensures the integrity of the blockchain by validating transactions. Validators have abilities that focus on defense and support.',
    thumbnail: 'Media/Classes/Validator/MVALIDATOR.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Validator',
    description: 'Ensures the integrity of the blockchain by validating transactions. Validators have abilities that focus on defense and support.',
    thumbnail: 'Media/Classes/Validator/FVALIDATOR.jpg',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Industrial Miner',
    description: 'Volcano Powered, Focused on maximizing mining efficiency, Industrial Miners excel in dealing high damage over a short period',
    thumbnail: 'Media/Classes/Industrial Miner/MINDUSTRIAL.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Industrial Miner',
    description: 'Volcano Powered, Focused on maximizing mining efficiency, Industrial Miners excel in dealing high damage over a short period',
    thumbnail: 'Media/Classes/Industrial Miner/FINDUSTRIAL.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'High Frequency Trader',
    description: 'Specializes in Lightning Fast trades and quick movements, allowing for swift attacks and dodges.',
    thumbnail: 'Media/Classes/HFT/MHFT.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'High Frequency Trader',
    description: 'Specializes in Lightning Fast trades and quick movements, allowing for swift attacks and dodges.',
    thumbnail: 'Media/Classes/HFT/FHFT.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Liquid Staker',
    description: 'Liquidity is king. Focused on being flezible and being ready for any kind of eventuality',
    thumbnail: 'Media/Classes/Liquid/MLIQUID.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Liquid Staker',
    description: 'For her Liquidity is king. Focused on being flexible and being ready for any kind of eventuality',
    thumbnail: 'Media/Classes/Liquid/FLIQUID.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Dormant Holder',
    description: 'Passively holds assets for extended periods, waiting for the right moment to re-engage.',
    thumbnail: 'Media/Classes/Dormant Holder/MDORMANT.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Dormant Holder',
    description: 'Passively holds assets for extended periods, waiting for the right moment to re-engage.',
    thumbnail: 'Media/Classes/Dormant Holder/FDORMANT.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Solo Node Runner',
    description: 'Operates independently, running a node to support the network, resilient and resourceful.',
    thumbnail: 'Media/Classes/Solo Node Runner/MSOLONODERUNNER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Solo Node Runner',
    description: 'Operates independently, Maintains the networks infrastructure.',
    thumbnail: 'Media/Classes/Solo Node Runner/FSOLONODERUNNER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Sniper',
    description:  'Patiently waits for the shot of a lifetime, relies on a lot of infra to get it done.',
    thumbnail: 'Media/Classes/Sniper/MSNIPER.png',
    abilities: [], 
},
{
    class: 'Survivor',
    title: 'Sniper',
    description:  'Unexpected a lethal to both developers and casual participants of the markets',
    thumbnail: 'Media/Classes/Sniper/FSNIPER.png',
    abilities: [], 
},
{
    class: 'Survivor',
    title: 'Governance Staker',
    description: 'Focuses on stability and long-term planning, providing buffs and enhancements over time.',
    thumbnail: 'Media/Classes/Governance Staker/MGOV.jpg',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Governance Staker',
    description: 'Focuses on stability and long-term planning, providing buffs and enhancements over time.',
    thumbnail: 'Media/Classes/Governance Staker/FGOV.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Yield Farmer',
    description: 'Experts at maximizing return by risking their capital, Yield Farmers excel at generating resources.',
    thumbnail: 'Media/Classes/Farmer/MFARMER.png',
    abilities: [], 
},{
    class: 'Survivor',
    title: 'Yield Farmer',
    description: 'Experts at maximizing return by risking their capital, Yield Farmers excel at generating resources.',
    thumbnail: 'Media/Classes/Farmer/FFARMER.png',
    abilities: [], 
},
{
    class: 'Survivor',
    title: 'Venture Capital',
    description: 'Masters of funding and investment, venture capitalists provide powerful buffs and debuffs related to resource management.',
    thumbnail: 'Media/Classes/Venture Capital/MVC.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Venture Capital',
    description: 'Masters of funding and investment, venture capitalists provide powerful buffs and debuffs related to resource management.',
    thumbnail: 'Media/Classes/Venture Capital/FVC.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Decentralization Trillemma Solver',
    description: 'In the search to solve Balances security, scalability, and decentralization.',
    thumbnail: 'Media/Classes/Trillemma Solver/MSOLVER.jpg',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Decentralization Trillemma Solver',
    description: 'In the search to solve Balances security, scalability, and decentralization.',
    thumbnail: 'Media/Classes/Trillemma Solver/FSOLVER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Tether Truther',
    description: 'They hated him because he told the truth.',
    thumbnail: 'Media/Classes/TRUTHER/MTRUTHER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Tether Truther',
    description: 'They hated her because she told the truth.',
    thumbnail: 'Media/Classes/TRUTHER/FTRUTHER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Mercerany Capital',
    description: 'High control of the markets, quick to take profits, regardless of the effects his actions might take on others peoples life.',
    thumbnail: 'Media/Classes/Mercenary Capital/MMERCENARY.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Mercerany Capital',
    description: 'High control of the markets, quick to take profits, regardless of the effects his actions might take on others peoples life.',
    thumbnail: 'Media/Classes/Mercenary Capital/FMERCENARY.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Copy Trader',
    description: 'Excels at observing and analyzing the strategies of successful traders, seamlessly replicating their moves in real-time.',
    thumbnail: 'Media/Classes/Copy Trader/MCOPYTRADER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Copy Trader',
    description: 'Excels at observing and analyzing the trading strategies of successful traders, seamlessly replicating their moves in real-time.',
    thumbnail: 'Media/Classes/Copy Trader/FCOPYTRADER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Policy Maker',
    description: 'Focuses on creating and implementing laws and policies that impact the industry.',
    thumbnail: 'Media/Classes/Policy Maker/MPOLICYMAKER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Policy Maker',
    description: 'Focuses on creating and implementing laws and policies that impact the industry.',
    thumbnail: 'Media/Classes/Policy Maker/FPOLICYMAKER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Angel Investor',
    description: 'Angel Investors provide the essential resources and stability needed to nurture fledgling projects from concept to reality.',
    thumbnail: 'Media/Classes/Angel/MANGEL.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Angel Investor',
    description: 'Angel Investors provide the essential resources and stability needed to nurture fledgling projects from concept to reality.',
    thumbnail: 'Media/Classes/Angel/FANGEL.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Holder',
    description: 'Masters of holding assets, they ride the waves of volatility with unshakeable resolve.',
    thumbnail: 'Media/Classes/Holder/MHOLDER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Holder',
    description: 'Dedicated to holding their assets for long-term gain. HODLers have high resilience and can endure prolonged battles.',
    thumbnail: 'Media/Classes/Holder/FHOLDER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'C.E.X. C.E.O.',
    description: 'Leader of a centralized exchange, skilled in navigating regulatory landscapes and market strategies.',
    thumbnail: 'Media/Classes/CEX/MCEX.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'C.E.X. C.E.O.',
    description: 'Leader of a centralized exchange, skilled in navigating regulatory landscapes and market strategies.',
    thumbnail: 'Media/Classes/CEX/FCEX.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'USD Maxi',
    description: 'Dedicated to stablecoins, prioritizes security and stability over volatility.',
    thumbnail: 'Media/Classes/USD Maxi/MUSDMAXI.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'USD Maxi',
    description: 'Dedicated to stablecoins, prioritizes security and stability over volatility.',
    thumbnail: 'Media/Classes/USD Maxi/FUSDMAXI.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Market Maker',
    description: 'Provides liquidity and stabilizes markets, skilled in trading and risk management.',
    thumbnail: 'Media/Classes/Market Maker/MMARKETMAKER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Market Maker',
    description: 'Provides liquidity and stabilizes markets, skilled in trading and risk management.',
    thumbnail: 'Media/Classes/Market Maker/FMARKETMAKER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Wallet Maker',
    description: 'Expert in creating secure and user-friendly digital wallets, critical to ecosystem growth.',
    thumbnail: 'Media/Classes/Wallet Maker/MWALLETMAKER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Wallet Maker',
    description: 'Expert in creating secure and user-friendly digital wallets, critical to ecosystem growth.',
    thumbnail: 'Media/Classes/Wallet Maker/FWALLETMAKER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Oracle',
    description: 'Bridges blockchain with real-world data, essential for smart contract execution.',
    thumbnail: 'Media/Classes/Oracle/MORACLE.jpg',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Oracle',
    description: 'Bridges blockchain with real-world data, essential for smart contract execution.',
    thumbnail: 'Media/Classes/Oracle/FORACLE.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Whale',
    description: 'Holds significant assets, able to influence markets and project outcomes with their moves.',
    thumbnail: 'Media/Classes/Whale/MWHALE.png',
    abilities: [], 
},
{
    class: 'Survivor',
    title: 'Whale',
    description: 'Holds significant assets, able to influence markets and project outcomes with their moves.',
    thumbnail: 'Media/Classes/Whale/FWHALE.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Shrimp',
    description: 'Small player in the crypto space, adaptable, flexible but his hand is forced by higher market forces.',
    thumbnail: 'Media/Classes/Shrimp/MSHRIMP.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Shrimp',
    description: 'Small player in the crypto space vulnerable and pushed by market swings.',
    thumbnail: 'Media/Classes/Shrimp/FSHRIMP.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'LARP',
    description: 'Masters of deception, creating narratives that may or may not be true, thrives on attention.',
    thumbnail: 'Media/Classes/LARP/MLARP.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'LARP',
    description: 'Masters of deception, creating narratives that may or may not be true, thrives on attention.',
    thumbnail: 'Media/Classes/LARP/FLARP.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Grifter',
    description: 'Masters of manipulation and persuasion, skilled in exploiting others for personal gain.',
    thumbnail: 'Media/Classes/Grifter/MGRIFTER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Grifter',
    description: 'Masters of manipulation and persuasion, skilled in exploiting others for personal gain.',
    thumbnail: 'Media/Classes/Grifter/FGRIFTER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'NFT Artist',
    description: 'The imaginative and artistic minds behind the digital art and collectibles on the blockchain',
    thumbnail: 'Media/Classes/NFT Artist/MNFTARTIST.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'NFT Artist',
    description: 'Enthusiasts creator of digital collectibles, focused on art, utility, and ownership within the blockchain.',
    thumbnail: 'Media/Classes/NFT Artist/FNFTARTIST.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'NFT Collector',
    description: 'Seeks out unique digital art pieces, driven by aesthetics and potential future value.',
    thumbnail: 'Media/Classes/NFT Collector/MNFTCOLLECTOR.png',
    abilities: [],

},
{
    class: 'Survivor',
    title: 'NFT Collector',
    description: 'Seeks out unique digital art pieces, driven by aesthetics and potential future value.',
    thumbnail: 'Media/Classes/NFT Collector/FNFTCOLLECTOR.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'CTO Leader',
    description: 'Technical mastermind, leads projects and innovations, critical to tech development in the space.',
    thumbnail: 'Media/Classes/CTO Leader/MCTOLEADER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'CTO Leader',
    description: 'Technical mastermind, leads projects and innovations, critical to tech development in the space.',
    thumbnail: 'Media/Classes/CTO Leader/FCTOLEADER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Serial Scammer',
    description: 'Repeatedly creates fraudulent schemes, skilled at evading consequences and exploiting others.',
    thumbnail: 'Media/Classes/Serial Scammer/MSERIALSCAMMER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Serial Scammer',
    description: 'Repeatedly creates fraudulent schemes, skilled at evading consequences and exploiting others.',
    thumbnail: 'Media/Classes/Serial Scammer/FSERIALSCAMMER.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Bagholder',
    description: 'Caught holding assets after a market downturn, enduring the lows in hopes of a recovery.',
    thumbnail: 'Media/Classes/Bagholder/MBAGHOLDER.png',
    abilities: [], 
},{
    class: 'Survivor',
    title: 'Bagholder',
    description: 'Caught holding assets after a market downturn, enduring the lows in hopes of a recovery.',
    thumbnail: 'Media/Classes/Bagholder/FBAGHOLDER.png',
    abilities: [], 
},{
    class: 'Survivor',
    title: 'Community Member',
    description: 'A true believer, fanatic of the assets hes holding, he cannot contain his excitement.',
    thumbnail: 'Media/Classes/Community Member/MCOMMUNITYMEMBER.png',
    abilities: [], 
},{
    class: 'Survivor',
    title: 'Community Member',
    description: 'A true believer, fanatic of the assets shes holding, she cannot contain his excitement.',
    thumbnail: 'Media/Classes/Community Member/FCOMMUNITYMEMBER.png',
    abilities: [], 
},
{
    class: 'Survivor',
    title: 'ICO Pioneer',
    description: 'Trailblazer in the crypto world, exploring new frontiers and setting trends.',
    thumbnail: 'Media/Classes/Pioneer/MPIONEER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'ICO Pioneer',
    description: 'Trailblazer in the crypto world, exploring new frontiers and setting trends.',
    thumbnail: 'Media/Classes/Pioneer/FPIONEER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Defi Native',
    description: 'Deeply rooted in decentralized finance, never interacted with the traditional system.',
    thumbnail: 'Media/Classes/Defi Native/MDEFINATIVE.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Defi Native',
    description: 'Adept at navigating complex protocols and strategies. Was born and raised inside the chain',
    thumbnail: 'Media/Classes/Defi Native/FDEFINATIVE.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Metaverse Landowner',
    description: 'Owns digital land in the metaverse, shaping virtual landscapes and communities.',
    thumbnail: 'Media/Classes/Metaverse Landowner/MMETAVERSELANDOWNER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Metaverse Landowner',
    description: 'Owns digital land in the metaverse, shaping virtual landscapes and communities.',
    thumbnail: 'Media/Classes/Metaverse Landowner/FMETAVERSELANDOWNER.png',
    abilities: [],
},

{
    class: 'Survivor',
    title: 'MEVil Genius',
    description: 'Possesses unmatched intellect and ruthlessness, capable of devising complex and malicious plans.',
    thumbnail: 'Media/Classes/Evil Genius/MEVILGENIUS.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'MEVil Genius',
    description: 'Possesses unmatched intellect and ruthlessness, capable of devising complex and malicious plans.',
    thumbnail: 'Media/Classes/Evil Genius/FEVILGENIUS.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Ponzi Designer',
    description: 'Expert at crafting deceptive schemes, enticing others with false promises of high returns.',
    thumbnail: 'Media/Classes/Ponzi Designer/MPONZIDESIGNER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Ponzi Designer',
    description: 'Expert at crafting deceptive schemes, enticing others with false promises of high returns.',
    thumbnail: 'Media/Classes/Ponzi Designer/FPONZIDESIGNER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Caller',
    description: 'Spreads the word about fraudulent schemes, luring others into the trap with charisma and false hope.',
    thumbnail: 'Media/Classes/Caller/MCALLER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Caller',
    description: 'Spreads the word about fraudulent schemes, luring others into the trap with charisma and false hope.',
    thumbnail: 'Media/Classes/Caller/FCALLER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Backstabber',
    description: 'Untrustworthy and opportunistic, willing to betray allies for personal gain.',
    thumbnail: 'Media/Classes/Backstabber/MBACKSTABBER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Backstabber',
    description: 'Untrustworthy and opportunistic, willing to betray allies for personal gain.',
    thumbnail: 'Media/Classes/Backstabber/FBACKSTABBER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Trencher',
    description: 'Hardened and resilient, thrives in harsh environments, committed to long-term survival.',
    thumbnail: 'Media/Classes/Trencher/MTRENCHER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Trencher',
    description: 'Hardened and resilient, thrives in harsh environments, committed to long-term survival.',
    thumbnail: 'Media/Classes/Trencher/FTRENCHER.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Beggar',
    description: 'Desperate and resourceful, survives by any means necessary, often relying on the charity of others.',
    thumbnail: 'Media/Classes/Beggar/MBEGGAR.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Beggar',
    description: 'Desperate and resourceful, survives by any means necessary, often relying on the charity of others.',
    thumbnail: 'Media/Classes/Beggar/FBEGGAR.png',
    abilities: [], 
},
{
    class: 'Survivor',
    title: 'Protagonist',
    description: 'The center of attention of all survivors, albeit short lived, has a profound effect in the collective consciousness',
    thumbnail: 'Media/Classes/Protagonist/MPROTAG.png',
    abilities: [], 
},
{
    class: 'Survivor',
    title: 'Protagonist',
    description:  'The center of attention of all survivors, albeit short lived, has a profound effect in the collective consciousness',
    thumbnail: 'Media/Classes/Protagonist/FPROTAG.png',
    abilities: [], 
},
{
    class: 'Survivor',
    title: 'Intern',
    description:  'Fresh faces in the blockchain space, eager to learn and make their mark. They are fast learners with a knack for problem-solving and innovation',
    thumbnail: 'Media/Classes/Intern/MINTERN.png',
    abilities: [], 
},
{
    class: 'Survivor',
    title: 'Intern',
    description:  'Fresh faces in the blockchain space, eager to learn and make their mark. They are fast learners with a knack for problem-solving and innovation',
    thumbnail: 'Media/Classes/Intern/FINTERN.png',
    abilities: [], 
},
{
    class: 'Survivor',
    title: 'Mod',
    description: 'Vigilant guardians of online communities, Mods keep the peace, enforce rules, and ensure that discussions remain on track, even in the most chaotic of times.',
    thumbnail: 'Media/Classes/Mod/MMOD.png',
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Mod',
    description: 'Vigilant guardians of online communities, Mods keep the peace, enforce rules, and ensure that discussions remain on track, even in the most chaotic of times.',
    thumbnail: 'Media/Classes/Mod/FMOD.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Seedless Survivor',
    description: 'Struggles to navigate the blockchain wilderness after losing their private seed phrase. This class focuses on resourcefulness and the determination to rebuild what was lost.',
    thumbnail: 'Media/Classes/Seedless/MSEEDLESS.png',
    abilities: [],
},{
    class: 'Survivor',
    title: 'Seedless Survivor',
    description: 'Struggles to navigate the blockchain wilderness after losing their private seed phrase. This class focuses on resourcefulness and the determination to rebuild what was lost.',
    thumbnail: 'Media/Classes/Seedless/FSEEDLESS.png',
    abilities: [],
}
];