export const playerTypes = [{
    class: 'Survivor',
    title: 'Onchain Survivor',
    description:'The jack of all trades (lol), adaptable and versatile with a balanced set of abilities that covers a wide range of effects.',
    tooltip:'despite losing it all in the 2018 market crash, he kept grinding every day.',
    health: 1,
    movementspeed:0.5,
    xp: 0,
    evasion: 50,
    xpToNextLevel:10,
    tags: ['player'],
    thumbnail: 'Media/Classes/Onchain Survivor/MSURVIVOR.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),
    level:0,
    isLocked: false,
    abilities: [
        { type: 'Scalping Bot', level: 1 },
        { type: 'Onchain Trail', level: 1  },
        { type: 'Scalping Bot', level: 0 },
        { type: 'Onchain Trail', level: 0 },
        { type: 'Veil of Decentralization', level: 0 },
        { type: 'Onchain Trail', level: 0  },
        { type: 'Scalping Bot', level: 0 },
        { type: 'Onchain Trail', level: 0 },
        { type: 'Onchain Trail', level: 0 }, 
        { type: 'Veil of Decentralization', level: 0 }
    ],
},{
    class: 'Survivor',
    title: 'Onchain Survivor',
    description: 'The jill of all trades (lol), adaptable and versatile with a balanced set of abilities that covers a wide range of effects.',
    tooltip: 'Despite losing it all in the 2018 market crash, she kept grinding every day.',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50, 
    xpToNextLevel:10,
    tags: ['player'],
    thumbnail: 'Media/Classes/Onchain Survivor/FSURVIVOR.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),
    level:0,
    isLocked: false,
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Miner',
    description: 'Strong, durable, reliable, albeit somewhat slow, have higher chance of taking good rewards.',
    tooltip: 'Despite losing it all in the 2018 market crash, she kept grinding every day.',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50, 
    xpToNextLevel:10,
    tags: ['player'],
    thumbnail: 'Media/Classes/Miner/MMINER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),
    level:0,
    isLocked: false,
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Miner',
    description: 'Has a longer and battle tested proven record of protecting and surviving in the chain.',
    tooltip: 'Despite losing it all in the 2018 market crash, she kept grinding every day.',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50, 
    xpToNextLevel:10,
    tags: ['player'],
    thumbnail: 'Media/Classes/Miner/FMINER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),
    level:0,
    isLocked: false,
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Staker',
    description: 'Balanced in speed and strength, stakers gain bonuses for maintaining stability and have unique defensive abilities.',
    tooltip: 'Despite losing it all in the 2018 market crash, she kept grinding every day.',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50, 
    xpToNextLevel:10,
    tags: ['player'],
    thumbnail: 'Media/Classes/Staker/MSTAKER.png',  
    geometry: new THREE.BoxGeometry(1, 1, 1),
    level:0,
    isLocked: false,
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Staker',
    description: 'Balanced in speed and strength, stakers gain bonuses for maintaining stability and have unique defensive abilities.',
    tooltip: 'Despite losing it all in the 2018 market crash, she kept grinding every day.',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50, 
    xpToNextLevel:10,
    tags: ['player'],
    thumbnail: 'Media/Classes/Staker/FSTAKER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),
    level:0,
    isLocked: false,
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Trader',
    description: 'Fast and agile, traders can move quickly around the arena but have lower health. They have unique abilities related to market dynamics.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Trader/MTRADER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),
    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Trader',
    description: 'Fast and agile, traders can move quickly around the arena but have lower health. They have unique abilities related to market dynamics.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Trader/FTRADER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Developer',
    description: 'Versatile and strategic, developers can modify the environment and create powerful code-based attacks.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Developer/MDEVELOPER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Developer',
    description: 'Versatile and strategic, developers can modify the environment and create powerful code-based attacks.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Developer/FDEVELOPER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Regulator',
    description: 'Controllers of chaos, regulators can impose rules and restrictions on enemies, making them powerful crowd-control specialists.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Regulator/MREGULATOR.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Regulator',
    description: 'Controllers of chaos, regulators can impose rules and restrictions on enemies, making them powerful crowd-control specialists.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Regulator/FREGULATOR.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Quantum Cryptographer',
    description: 'Masters of quantum cryptography, withouth them the blockchain has no means of suriving in the future.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Quantum/MQUANTUM.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Quantum Cryptographer',
    description: 'Masters of quantum cryptography, withouth them the blockchain has no means of suriving in the future.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Quantum/FQUANTUM.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Crypto Botter',
    description: 'Utilizes bots and scripts for every action, very resourceful, always has an edge agaisnt other survivors.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Crypto Botter/MBOTTER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Crypto Botter',
    description: 'Utilizes bots and scripts for every action, very resourceful, always has an edge agaisnt other survivors.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Crypto Botter/FBOTTER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Fudder',
    description: 'Always bearish, spreading fear, uncertainty, and doubt (FUD). Fudders are unafected by the always improving  blockchain tech...',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Fudder/MFUDDER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Fudder',
    description: 'Always bearish, spreading fear, uncertainty, and doubt (FUD). Fudders are unafected by the always improving  blockchain tech...',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Fudder/FFUDDER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},
{
    class: 'Survivor',
    title: 'Crypto Astrologer',
    description: 'Uses the moon cycles and the stars and signs to predict market movements, providing unique takes based on astrological insights',
    tooltip: 'Some say he has more hidden wallets than *******.',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Astrologer/MASTROLOGER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [

    ],
},
{
    class: 'Survivor',
    title: 'Crypto Astrologer',
    description: 'Uses the moon cycles and the stars and signs to predict market movements, providing unique takes based on astrological insights',
    tooltip: 'Some say he has more hidden wallets than *******.',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Astrologer/FASTROLOGER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [

    ],
},
{
    class: 'Survivor',
    title: 'Influencer',
    description: 'Influencers have a huge following and can move markets with a single well timed post online. Tends to lean the vain side.',
    tooltip: 'Some say he has more hidden wallets than *******.',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Influencer/MINFLUENCER.jpg',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [

    ],
},
{
    class: 'Survivor',
    title: 'Influencer',
    description: 'Influencers have the ability to stand out in a crowded digital space. She has built her reputation from scratch',
    tooltip: 'Some say she has more hidden wallets than *******.',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Influencer/FINFLUENCER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [


    ],
},{
    class: 'Survivor',
    title: 'Cabal Insider',
    description: 'Part of the inner group that manipulates markets for their benefit. They are in control.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Insider Cabal/MCABAL.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Cabal Insider',
    description: 'Part of the inner group that manipulates markets for their benefit. They are in control.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Insider Cabal/FCABAL.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Bitcoin MAXI',
    description: 'Holds 100% of their net worth in a Bitcoin, Never selling, always holding.  Showcases unwavering faith.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Maxi/MMAXI.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Bitcoin MAXI',
    description: 'Holds 100% of their net worth in a Bitcoin, Never selling, always holding.  Showcases unwavering faith.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Maxi/FMAXI.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Gambler',
    description: 'Former poker player and sports bettor turned crypto enthusiast, thriving on risk.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Gambler/MGAMBLER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Gambler',
    description: 'Former poker player and sports bettor turned crypto enthusiast, thriving on risk.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Gambler/FGAMBLER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Liquidator',
    description: 'Specializes in liquidating loans and protocols, causing financial chaos.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Liquidator/MLIQUIDATOR.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Liquidator',
    description: 'Specializes in liquidating loans and protocols, causing financial chaos.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Liquidator/FLIQUIDATOR.png', // Debt: fix the green borders, make them black
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Nocoiner',
    description: 'Does not hold  any crypto currencies,  but spends all their time discussing crypto, spreading skepticism.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Nocoiner/MNOCOINER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Nocoiner',
    description: 'Does not hold  any crypto currencies,  but spends all their time discussing crypto, spreading skepticism.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Nocoiner/FNOCOINER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Auditor',
    description: 'Revises code to ensure it does not contain fatal bugs, preventing exploits',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Auditor/MAUDITOR.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Auditor',
    description: 'Revises code to ensure it does not contain fatal bugs, preventing exploits',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Auditor/FAUDITOR.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Sleuth',
    description: 'Tracks on-chain history to uncover events and catch criminals.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Sleuth/MSLEUTH.png', //Debt: add a pipe, make background black 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Sleuth',
    description: 'Tracks on-chain history to uncover events and catch criminals.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Sleuth/FSLEUTH.png', //Debt: add a pipe 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Beta Tester',
    description: 'Tests blockchain projects during beta, discovering strengths and weaknesses',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Beta Tester/MBETATESTER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Beta Tester',
    description: 'Tests blockchain projects during beta, discovering strengths and weaknesses',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Beta Tester/FBETATESTER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Defi Expert',
    description: 'Experts in utilizing decentralized finance protocols to gain advantages.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Defi/MDEFI.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Defi Expert',
    description: 'Experts in utilizing decentralized finance protocols to gain advantages.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Defi/FDEFI.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Defi Hacker',
    description: 'Skilled in infiltration and sabotage, drains protocols, exploiting vulnerabilities for personal gain',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Defi Hacker/MDEFIHACKER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Defi Hacker',
    description: 'Skilled in infiltration and sabotage, drains protocols, exploiting vulnerabilities for personal gain',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Defi Hacker/FDEFIHACKER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Sybiller',
    description: 'Uses multiple fake personas to forge voting results, airdrops, and more.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Sybiller/MSYBILLER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Sybiller',
    description: 'Uses multiple fake personas to forge voting results, airdrops, and more.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Sybiller/FSYBILLER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},
{
    class: 'Survivor',
    title: 'Validator',
    description: 'Ensures the integrity of the blockchain by validating transactions. Validators have abilities that focus on defense and support.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Validator/MVALIDATOR.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},
{
    class: 'Survivor',
    title: 'Validator',
    description: 'Ensures the integrity of the blockchain by validating transactions. Validators have abilities that focus on defense and support.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Validator/FVALIDATOR.jpg',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Industrial Miner',
    description: 'Volcano Powered, Focused on maximizing mining efficiency, Industrial Miners excel in dealing high damage over a short period',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Industrial Miner/MINDUSTRIAL.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},
{
    class: 'Survivor',
    title: 'Industrial Miner',
    description: 'Volcano Powered, Focused on maximizing mining efficiency, Industrial Miners excel in dealing high damage over a short period',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Industrial Miner/FINDUSTRIAL.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'High Frequency Trader',
    description: 'Specializes in Lightning Fast trades and quick movements, allowing for swift attacks and dodges.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/HFT/MHFT.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},
{
    class: 'Survivor',
    title: 'High Frequency Trader',
    description: 'Specializes in Lightning Fast trades and quick movements, allowing for swift attacks and dodges.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/HFT/FHFT.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Liquid Staker',
    description: 'Liquidity is king. Focused on being flezible and being ready for any kind of eventuality',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Liquid/MLIQUID.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Liquid Staker',
    description: 'For her Liquidity is king. Focused on being flexible and being ready for any kind of eventuality',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Liquid/FLIQUID.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Dormant Holder',
    description: 'Passively holds assets for extended periods, waiting for the right moment to re-engage.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.1,
    xp: 0,
    evasion: 20,
    tags: ['player'],
    thumbnail: 'Media/Classes/Dormant Holder/MDORMANT.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Dormant Holder',
    description: 'Passively holds assets for extended periods, waiting for the right moment to re-engage.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.1,
    xp: 0,
    evasion: 20,
    tags: ['player'],
    thumbnail: 'Media/Classes/Dormant Holder/FDORMANT.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},{
    class: 'Survivor',
    title: 'Solo Node Runner',
    description: 'Operates independently, running a node to support the network, resilient and resourceful.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.25,
    xp: 0,
    evasion: 40,
    tags: ['player'],
    thumbnail: 'Media/Classes/Solo Node Runner/MSOLONODERUNNER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Solo Node Runner',
    description: 'Operates independently, Maintains the networks infrastructure.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.25,
    xp: 0,
    evasion: 40,
    tags: ['player'],
    thumbnail: 'Media/Classes/Solo Node Runner/FSOLONODERUNNER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Sniper',
    description:  'Patiently waits for the shot of a lifetime, relies on a lot of infra to get it done.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.1,
    xp: 0,
    evasion: 30,
    tags: ['player'],
    thumbnail: 'Media/Classes/Sniper/MSNIPER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),
    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Sniper',
    description:  'Unexpected a lethal to both developers and casual participants of the markets',
    tooltip: '',    
    health: 1,
    movementspeed: 0.1,
    xp: 0,
    evasion: 30,
    tags: ['player'],
    thumbnail: 'Media/Classes/Sniper/FSNIPER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),
    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Governance Staker',
    description: 'Focuses on stability and long-term planning, providing buffs and enhancements over time.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Governance Staker/MGOV.jpg',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Governance Staker',
    description: 'Focuses on stability and long-term planning, providing buffs and enhancements over time.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Governance Staker/FGOV.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Yield Farmer',
    description: 'Experts at maximizing return by risking their capital, Yield Farmers excel at generating resources.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Farmer/MFARMER.png',  //Debt ADD PERSONALITY
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Yield Farmer',
    description: 'Experts at maximizing return by risking their capital, Yield Farmers excel at generating resources.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Farmer/FFARMER.png',  //Debt ADD PERSONALITY
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},
{
    class: 'Survivor',
    title: 'Venture Capital',
    description: 'Masters of funding and investment, venture capitalists provide powerful buffs and debuffs related to resource management.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Venture Capital/MVC.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Venture Capital',
    description: 'Masters of funding and investment, venture capitalists provide powerful buffs and debuffs related to resource management.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Venture Capital/FVC.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Decentralization Trillemma Solver',
    description: 'In the search to solve Balances security, scalability, and decentralization.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Trillemma Solver/MSOLVER.jpg',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Decentralization Trillemma Solver',
    description: 'In the search to solve Balances security, scalability, and decentralization.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Trillemma Solver/FSOLVER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Tether Truther',
    description: 'They hated him because he told the truth.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/TRUTHER/MTRUTHER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Tether Truther',
    description: 'They hated her because she told the truth.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/TRUTHER/FTRUTHER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false, 
    abilities: [

    ],
},{
    class: 'Survivor',
    title: 'Mercerany Capital',
    description: 'High control of the markets, quick to take profits, regardless of the effects his actions might take on others peoples life.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Mercenary Capital/MMERCENARY.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Mercerany Capital',
    description: 'High control of the markets, quick to take profits, regardless of the effects his actions might take on others peoples life.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Mercenary Capital/FMERCENARY.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Copy Trader',
    description: 'Excels at observing and analyzing the strategies of successful traders, seamlessly replicating their moves in real-time.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Copy Trader/MCOPYTRADER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Copy Trader',
    description: 'Excels at observing and analyzing the trading strategies of successful traders, seamlessly replicating their moves in real-time.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Copy Trader/FCOPYTRADER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Policy Maker',
    description: 'Focuses on creating and implementing laws and policies that impact the industry.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Policy Maker/MPOLICYMAKER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Policy Maker',
    description: 'Focuses on creating and implementing laws and policies that impact the industry.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Policy Maker/FPOLICYMAKER.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Angel Investor',
    description: 'Angel Investors provide the essential resources and stability needed to nurture fledgling projects from concept to reality.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Angel/MANGEL.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},{
    class: 'Survivor',
    title: 'Angel Investor',
    description: 'Angel Investors provide the essential resources and stability needed to nurture fledgling projects from concept to reality.',
    tooltip: '',    
    health: 1,
    movementspeed:0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Angel/FANGEL.png',
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level:0,
    isLocked: false,
    abilities: [
  
    ],
},
{
    class: 'Survivor',
    title: 'Holder',
    description: 'Masters of holding assets, they ride the waves of volatility with unshakeable resolve.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.15,
    xp: 0,
    evasion: 30,
    tags: ['player'],
    thumbnail: 'Media/Classes/Holder/MHOLDER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Holder',
    description: 'Dedicated to holding their assets for long-term gain. HODLers have high resilience and can endure prolonged battles.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.15,
    xp: 0,
    evasion: 30,
    tags: ['player'],
    thumbnail: 'Media/Classes/Holder/FHOLDER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'C.E.X. C.E.O.',
    description: 'Leader of a centralized exchange, skilled in navigating regulatory landscapes and market strategies.',
    tooltip: '',    
    health: 3,
    movementspeed: 0.1,
    xp: 0,
    evasion: 20,
    tags: ['player'],
    thumbnail: 'Media/Classes/CEX/MCEX.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'C.E.X. C.E.O.',
    description: 'Leader of a centralized exchange, skilled in navigating regulatory landscapes and market strategies.',
    tooltip: '',    
    health: 3,
    movementspeed: 0.1,
    xp: 0,
    evasion: 20,
    tags: ['player'],
    thumbnail: 'Media/Classes/CEX/FCEX.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'USD Maxi',
    description: 'Dedicated to stablecoins, prioritizes security and stability over volatility.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.15,
    xp: 0,
    evasion: 35,
    tags: ['player'],
    thumbnail: 'Media/Classes/USD Maxi/MUSDMAXI.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'USD Maxi',
    description: 'Dedicated to stablecoins, prioritizes security and stability over volatility.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.15,
    xp: 0,
    evasion: 35,
    tags: ['player'],
    thumbnail: 'Media/Classes/USD Maxi/FUSDMAXI.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Market Maker',
    description: 'Provides liquidity and stabilizes markets, skilled in trading and risk management.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.2,
    xp: 0,
    evasion: 40,
    tags: ['player'],
    thumbnail: 'Media/Classes/Market Maker/MMARKETMAKER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Market Maker',
    description: 'Provides liquidity and stabilizes markets, skilled in trading and risk management.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.2,
    xp: 0,
    evasion: 40,
    tags: ['player'],
    thumbnail: 'Media/Classes/Market Maker/FMARKETMAKER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Wallet Maker',
    description: 'Expert in creating secure and user-friendly digital wallets, critical to ecosystem growth.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Wallet Maker/MWALLETMAKER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Wallet Maker',
    description: 'Expert in creating secure and user-friendly digital wallets, critical to ecosystem growth.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.2,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Wallet Maker/FWALLETMAKER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Oracle',
    description: 'Bridges blockchain with real-world data, essential for smart contract execution.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.2,
    xp: 0,
    evasion: 45,
    tags: ['player'],
    thumbnail: 'Media/Classes/Oracle/MORACLE.jpg', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Oracle',
    description: 'Bridges blockchain with real-world data, essential for smart contract execution.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.2,
    xp: 0,
    evasion: 45,
    tags: ['player'],
    thumbnail: 'Media/Classes/Oracle/FORACLE.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Whale',
    description: 'Holds significant assets, able to influence markets and project outcomes with their moves.',
    tooltip: '',    
    health: 3,
    movementspeed: 0.1,
    xp: 0,
    evasion: 20,
    tags: ['player'],
    thumbnail: 'Media/Classes/Whale/MWHALE.png', 
    geometry: new THREE

.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Whale',
    description: 'Holds significant assets, able to influence markets and project outcomes with their moves.',
    tooltip: '',    
    health: 3,
    movementspeed: 0.1,
    xp: 0,
    evasion: 20,
    tags: ['player'],
    thumbnail: 'Media/Classes/Whale/FWHALE.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Shrimp',
    description: 'Small player in the crypto space, adaptable, flexible but his hand is forced by higher market forces.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.25,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Shrimp/MSHRIMP.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Shrimp',
    description: 'Small player in the crypto space vulnerable and pushed by market swings.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.25,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Shrimp/FSHRIMP.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'LARP',
    description: 'Masters of deception, creating narratives that may or may not be true, thrives on attention.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.2,
    xp: 0,
    evasion: 45,
    tags: ['player'],
    thumbnail: 'Media/Classes/LARP/MLARP.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'LARP',
    description: 'Masters of deception, creating narratives that may or may not be true, thrives on attention.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.2,
    xp: 0,
    evasion: 45,
    tags: ['player'],
    thumbnail: 'Media/Classes/LARP/FLARP.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Grifter',
    description: 'Masters of manipulation and persuasion, skilled in exploiting others for personal gain.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.25,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Grifter/MGRIFTER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Grifter',
    description: 'Masters of manipulation and persuasion, skilled in exploiting others for personal gain.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.25,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Grifter/FGRIFTER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'NFT Artist',
    description: 'The imaginative and artistic minds behind the digital art and collectibles on the blockchain',
    tooltip: '',    
    health: 1,
    movementspeed: 0.2,
    xp: 0,
    evasion: 40,
    tags: ['player'],
    thumbnail: 'Media/Classes/NFT Artist/MNFTARTIST.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'NFT Artist',
    description: 'Enthusiasts creator of digital collectibles, focused on art, utility, and ownership within the blockchain.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.2,
    xp: 0,
    evasion: 40,
    tags: ['player'],
    thumbnail: 'Media/Classes/NFT Artist/FNFTARTIST.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'NFT Collector',
    description: 'Seeks out unique digital art pieces, driven by aesthetics and potential future value.',
    tooltip: '',
    health: 1,
    movementspeed: 0.2,
    xp: 0,
    evasion: 35,
    tags: ['player'],
    thumbnail: 'Media/Classes/NFT Collector/MNFTCOLLECTOR.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'NFT Collector',
    description: 'Seeks out unique digital art pieces, driven by aesthetics and potential future value.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.2,
    xp: 0,
    evasion: 35,
    tags: ['player'],
    thumbnail: 'Media/Classes/NFT Collector/FNFTCOLLECTOR.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'CTO Leader',
    description: 'Technical mastermind, leads projects and innovations, critical to tech development in the space.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.15,
    xp: 0,
    evasion: 35,
    tags: ['player'],
    thumbnail: 'Media/Classes/CTO Leader/MCTOLEADER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'CTO Leader',
    description: 'Technical mastermind, leads projects and innovations, critical to tech development in the space.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.15,
    xp: 0,
    evasion: 35,
    tags: ['player'],
    thumbnail: 'Media/Classes/CTO Leader/FCTOLEADER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Serial Scammer',
    description: 'Repeatedly creates fraudulent schemes, skilled at evading consequences and exploiting others.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.3,
    xp: 0,
    evasion: 60,
    tags: ['player'],
    thumbnail: 'Media/Classes/Serial Scammer/MSERIALSCAMMER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Serial Scammer',
    description: 'Repeatedly creates fraudulent schemes, skilled at evading consequences and exploiting others.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.3,
    xp: 0,
    evasion: 60,
    tags: ['player'],
    thumbnail: 'Media/Classes/Serial Scammer/FSERIALSCAMMER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},{
    class: 'Survivor',
    title: 'Bagholder',
    description: 'Caught holding assets after a market downturn, enduring the lows in hopes of a recovery.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.3,
    xp: 0,
    evasion: 60,
    tags: ['player'],
    thumbnail: 'Media/Classes/Bagholder/MBAGHOLDER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},{
    class: 'Survivor',
    title: 'Bagholder',
    description: 'Caught holding assets after a market downturn, enduring the lows in hopes of a recovery.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.3,
    xp: 0,
    evasion: 60,
    tags: ['player'],
    thumbnail: 'Media/Classes/Bagholder/FBAGHOLDER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},{
    class: 'Survivor',
    title: 'Pioneer',
    description: 'Trailblazer in the crypto world, exploring new frontiers and setting trends.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.2,
    xp: 0,
    evasion: 40,
    tags: ['player'],
    thumbnail: 'Media/Classes/Pioneer/MPIONEER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Pioneer',
    description: 'Trailblazer in the crypto world, exploring new frontiers and setting trends.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.2,
    xp: 0,
    evasion: 40,
    tags: ['player'],
    thumbnail: 'Media/Classes/Pioneer/FPIONEER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Defi Native',
    description: 'Deeply rooted in decentralized finance, never interacted with the traditional system.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.2,
    xp: 0,
    evasion: 35,
    tags: ['player'],
    thumbnail: 'Media/Classes/Defi Native/MDEFINATIVE.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Defi Native',
    description: 'Adept at navigating complex protocols and strategies. Was born and raised inside the chain',
    tooltip: '',    
    health: 2,
    movementspeed: 0.2,
    xp: 0,
    evasion: 35,
    tags: ['player'],
    thumbnail: 'Media/Classes/Defi Native/FDEFINATIVE.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Metaverse Landowner',
    description: 'Owns digital land in the metaverse, shaping virtual landscapes and communities.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.15,
    xp: 0,
    evasion: 30,
    tags: ['player'],
    thumbnail: 'Media/Classes/Metaverse Landowner/MMETAVERSELANDOWNER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Metaverse Landowner',
    description: 'Owns digital land in the metaverse, shaping virtual landscapes and communities.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.15,
    xp: 0,
    evasion: 30,
    tags: ['player'],
    thumbnail: 'Media/Classes/Metaverse Landowner/FMETAVERSELANDOWNER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},

{
    class: 'Survivor',
    title: 'MEVil Genius',
    description: 'Possesses unmatched intellect and ruthlessness, capable of devising complex and malicious plans.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.15,
    xp: 0,
    evasion: 45,
    tags: ['player'],
    thumbnail: 'Media/Classes/Evil Genius/MEVILGENIUS.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'MEVil Genius',
    description: 'Possesses unmatched intellect and ruthlessness, capable of devising complex and malicious plans.',
    tooltip: '',    
    health: 2,
    movementspeed: 0.15,
    xp: 0,
    evasion: 45,
    tags: ['player'],
    thumbnail: 'Media/Classes/Evil Genius/FEVILGENIUS.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Ponzi Designer',
    description: 'Expert at crafting deceptive schemes, enticing others with false promises of high returns.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.25,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Ponzi Designer/MPONZIDESIGNER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Ponzi Designer',
    description: 'Expert at crafting deceptive schemes, enticing others with false promises of high returns.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.25,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Ponzi Designer/FPONZIDESIGNER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Caller',
    description: 'Spreads the word about fraudulent schemes, luring others into the trap with charisma and false hope.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.3,
    xp: 0,
    evasion: 55,
    tags: ['player'],
    thumbnail: 'Media/Classes/Caller/MCALLER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Caller',
    description: 'Spreads the word about fraudulent schemes, luring others into the trap with charisma and false hope.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.3,
    xp: 0,
    evasion: 55,
    tags: ['player'],
    thumbnail: 'Media/Classes/Caller/FCALLER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Backstabber',
    description: 'Untrustworthy and opportunistic, willing to betray allies for personal gain.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.25,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Backstabber/MBACKSTABBER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Backstabber',
    description: 'Untrustworthy and opportunistic, willing to betray allies for personal gain.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.25,
    xp: 0,
    evasion: 50,
    tags: ['player'],
    thumbnail: 'Media/Classes/Backstabber/FBACKSTABBER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Trencher',
    description: 'Hardened and resilient, thrives in harsh environments, committed to long-term survival.',
    tooltip: '',    
    health: 3,
    movementspeed: 0.1,
    xp: 0,
    evasion: 20,
    tags: ['player'],
    thumbnail: 'Media/Classes/Trencher/MTRENCHER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Trencher',
    description: 'Hardened and resilient, thrives in harsh environments, committed to long-term survival.',
    tooltip: '',    
    health: 3,
    movementspeed: 0.1,
    xp: 0,
    evasion: 20,
    tags: ['player'],
    thumbnail: 'Media/Classes/Trencher/FTRENCHER.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Beggar',
    description: 'Desperate and resourceful, survives by any means necessary, often relying on the charity of others.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.1,
    xp: 0,
    evasion: 30,
    tags: ['player'],
    thumbnail: 'Media/Classes/Beggar/MBEGGAR.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),

    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Beggar',
    description: 'Desperate and resourceful, survives by any means necessary, often relying on the charity of others.',
    tooltip: '',    
    health: 1,
    movementspeed: 0.1,
    xp: 0,
    evasion: 30,
    tags: ['player'],
    thumbnail: 'Media/Classes/Beggar/FBEGGAR.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),
    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Protagonist',
    description: 'The center of attention of all survivors, albeit short lived, has a profound effect in the collective consciousness',
    tooltip: '',    
    health: 1,
    movementspeed: 0.1,
    xp: 0,
    evasion: 30,
    tags: ['player'],
    thumbnail: 'Media/Classes/Protagonist/MPROTAG.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),
    level: 0,
    isLocked: false,
    abilities: [],
},
{
    class: 'Survivor',
    title: 'Protagonist',
    description:  'The center of attention of all survivors, albeit short lived, has a profound effect in the collective consciousness',
    tooltip: '',    
    health: 1,
    movementspeed: 0.1,
    xp: 0,
    evasion: 30,
    tags: ['player'],
    thumbnail: 'Media/Classes/Protagonist/FPROTAG.png', 
    geometry: new THREE.BoxGeometry(1, 1, 1),
    level: 0,
    isLocked: false,
    abilities: [],
}
];