export const abilityTypes = [
    {title: "Frontrunning Bot",
        description: "A fast bot that outpaces you and your enemy movements.",
        thumbnail: 'src/Media/Abilities/FRONTRUNNINGBOT.png',
        effect: [
            "Create Bot",
            "Frontrun"
        ],
    }]
    
    /*
    ,
    {title: "Scalping Bot",
        description: 'Abusing the market volatility, The Scalping bot Executes incredibly fast attacks.',
        thumbnail: 'src/Media/Abilities/SCALPINGBOT.png',
        effect: [
            "Create Bot",
            "Scalp"
        ],
    },
    {title: "Sniping Bot",
        description: "Fast trading bot that liquidates opposing survivors.",
        thumbnail: 'src/Media/Abilities/SNIPEBOT.png',
        effect: [
            "Create Bot",
            "Elevate",
            "Frontrun",
            "Point Laser",
            "Shoot Closest Enemy", 
        ],
    }, 
    {title: "Blockchain Backup",
        description: "The survivor keeps a backup of everything always in handy.",
        thumbnail: 'src/Media/Abilities/BLOCKCHAINBACKUP.png',
        effect: [
            "Create Bot",
            "Follow Close"
        ],
    }, 
    {title: "Data Blob",
        description: "the survivor heavily brings along a big blob of data holding a piece of the blockchain",
        thumbnail: 'src/Media/Abilities/BLOB.png',
        effect: [
            "Create Bot",
            "Follow Far"
        ],
    },
    {title: "Exploit Finder",
        description: "Scans the blockchain for harmful elements and neutralizes them.",
        thumbnail: "src/Media/Abilities/EXPLOITFINDER.png",
        effect: [
            "Create Bot",
            "Orbit"
        ],
    },
    { title: 'Onchain Trail',
        description: 'Your onchain movements leave a trail behind, damaging pursuers',
        thumbnail: 'src/Media/Abilities/ONCHAINTRAIL.png',
        effect: [
            "Create Trail Step",
            "Manage Trail",
        ],
    },
    {title: "Veil of Decentralization",
        description: "The Survivor shrouds in decentralization, becoming greatly elusive.",
        thumbnail: 'src/Media/Abilities/VEILOFDECENTRALIZATION.png',
        effect: [
            "Create Veil",
            "EvasionUP"
        ],
    },
    {title: "Bot Swarm",
        description: "Summons additional bots to assist in battle.",
        thumbnail: 'src/Media/Abilities/SWARM.png',
        effect: [
            "Create Bot",
            "Swarm"
        ],
    },
    {title: "Anti-Rug Bot",
        description: "Detects and disables rug traps.",
        thumbnail: 'src/Media/Abilities/RUGBOT.png',
        effect: [
            "Create Bot",
            "Swipe"
        ],
    },
{
    title: "Code Refactor",
    description: "Rewrites and optimizes the Survivor's abilities, reducing their cooldowns.",
    thumbnail: 'src/Media/Abilities/CODEREFACTOR.png',
    effect: [],
},{
    title: "Sybil Attack",
    description: "Creates multiples identities, disorienting and damaging enemies.",
    thumbnail:'src/Media/Abilities/SYBILATTACK.png',
    effect: [],
},{
    title: "Vote Manipulation",
    description: "Illegally uses the voting power of other survivors in range agaisnt their will, turning bonuses into penalties.",
    thumbnail: 'src/Media/Abilities/VOTEMANIPULATION.png',
    effect: [],
},{
    title: "Airdrop Fraud",
    description: "Free, fake tokens fall from the sky, draining the survivors who interact with them.",
    thumbnail: 'src/Media/Abilities/AIRDROPFRAUD.png', 
    effect: [], 
},{
    title: "Identity Forge",
    description: "Specializes in creating a whole new persona, gaining the bonuses of a random class.",
    thumbnail: 'src/Media/Abilities/IDENTITYFORGE.png', 
    effect: [], 
},{
    title: "Decentralized Vote Rigging",
    description: "By controlling the majority of the chain validators, the survivor gains a random bonus.",
    thumbnail: 'src/Media/Abilities/VOTERIGGING.png',
    effect: [], 
},{
    title: "Confirm Block",
    description: "As transactions become confirmed and secured overtime, the survivor gains defensive bonuses",
    thumbnail: 'src/Media/Abilities/CONFIRMBLOCK.png',
    effect: [], 
},
{
    title: "Finality",
    description: "The blockchain inmutality makes it so  buried Survivors can not ever revive, If they take more than 6 blocks.",
    thumbnail: 'src/Media/Abilities/FINALITY.png',
    effect: [], 
},{
    title: "Copy Trading",
    description: "Creates a shield that absorbs multiple hits.",
    thumbnail: 'src/Media/Abilities/COPYTRADING.png',
    effect: [],
},
{
    title: "Double Spend Prevention ",
    description: "Creates a shield that absorbs multiple hits.",
    thumbnail: 'src/Media/Abilities/DOUBLESPENDPREVENTION.png',
    effect: [],
},
{
    title: "Overclock",
    description: "Greatly increases attack power for a brief period.",
    thumbnail: 'src/Media/Abilities/OVERCLOCK.png',
    effect: [],
},
{
    title: "Mining Rig",
    description: "Deploys a stationary turret that automatically attacks enemies.",
    thumbnail: 'src/Media/Abilities/MININGRIG.png',
    effect: [],
},
{
    title: "Energy Surge",
    description: "Temporarily increases attack speed and movement speed.",
    thumbnail: 'src/Media/Abilities/ENERGYSURGE.png',
    effect: [],
},
{
    title: "PoS Migration",
    description: "Increases the player's defense.",
    thumbnail: 'src/Media/Abilities/POSMIGRATION.png',
    effect: [],
},
{
    title: "PoW Migration ",
    description: "Increases the player's attack power.",
    thumbnail: 'src/Media/Abilities/POWMIGRATION.png',
    effect: [],
},
{
    title: "Governance Vote",
    description: "Grants a random beneficial effect based on player needs.",
    thumbnail: 'src/Media/Abilities/GOVERNANCEVOTE.png',
    effect: [],
},
{
    title: "Protocol Upgrade",
    description: "Improves all abilities for a limited time.",
    thumbnail: "src/Media/Abilities/PROTOCOLUPGRADE.png",
    effect: [],
},
{
    title: "Network Upgrade ",
    description: "Grants a significant buff to a random ability.",
    thumbnail: "src/Media/Abilities/NETWORKUPGRADE.png",
    effect: [],
},
{
    title: "Quantum Encryption",
    description: "Creates a shield that reduces incoming damage.",
    thumbnail: "src/Media/Abilities/QUANTUMENCRYPTION.png",
    effect: [],
},{
    title: "Transaction Fee",
    description: "Reduces the cooldown of all abilities.",
    thumbnail: 'src/Media/Abilities/TRANSACTIONFEE.png',
    effect: [],
},
{
    title: "Transaction Fee Burn",
    description: "Reduces enemy resources by burning their assets.",
    thumbnail: 'src/Media/Abilities/FEEBURN.png',
    effect: [],
},
{
    title: "Whale Power",
    description: "Increases all stats for a short duration.",
    thumbnail: "src/Media/Abilities/WHALEPOWER.png",
    effect: [],
},
{
    title: "Block Reward",
    description: "Heals the player for a portion of damage dealt.",
    thumbnail: 'src/Media/Abilities/BLOCKREWARD.png',
    effect: [],
},
{
    title: "Crypto MultiSig",
    description: "Secures resources with multiple signatures.",
    thumbnail: 'src/Media/Abilities/CRYPTOMULTISIG.png',
    effect: [],
},{
    title: "Transaction Sign",
    description: "Secures resources with a single signature.",
    thumbnail: 'src/Media/Abilities/CRYPTOSIGN.png',
    effect: [],
},
{
    title: "Staking Rewards",
    description: "Provides periodic healing to all allies.",
    thumbnail: 'src/Media/Abilities/STAKINGREWARD.png',
    effect: [],
},
{
    title: "DAO Governance",
    description: "Empowers allies with decision-making buffs.",
    thumbnail: 'src/Media/Abilities/DAOGOVERNANCE.png',
    effect: [],
},
{
    title: "Finger Pointing",
    description: "Implements a major change, significantly debuffing enemies.",
    thumbnail: 'src/Media/Abilities/FINGER.png',
    effect: [],
},
{
    title: "Surprise Liquidation",
    description: "Causes a massive area-of-effect damage.",
    thumbnail: "src/Media/Abilities/LIQUIDATIONEVENT.png",
    effect: [],
},
{
    title: "Price Divergence ",
    description: "Confuses enemies, causing them to attack each other.",
    thumbnail: "src/Media/Abilities/DIVERGENCE.png",
    effect: [],
},
{
    title: "Compliance Order",
    description: "Forces enemies to move towards the player, taking damage over time.",
    thumbnail: "src/Media/Abilities/COMPLIANCEORDER.png",
    effect: [],
},{
    title: "Entanglement",
    description: "Links enemies, causing damage to spread among them.",
    thumbnail: "src/Media/Abilities/ENTANGLEMENT.png",
    effect: [],
},
{
    title: "Decentralized Network",
    description: "Summons allies to assist in battle.",
    thumbnail: 'src/Media/Abilities/DECENTRALIZEDNETWORK.png',
    effect: [],
},{
    title: "Liquidity Pool",
    description: "Creates a pool that heals allies and damages enemies.",
    thumbnail: 'src/Media/Abilities/LIQUIDITYPOOL.png',
    effect: [],
},{
    title: "Initial DEX Offering",
    description: "Increases allies' attack power.",
    thumbnail: 'src/Media/Abilities/INITIALDEXOFFERING.png',
    effect: [],
},{
    title: "No Coin FUD",
    description: "Decreases enemy attack power and movement speed.",
    thumbnail: "src/Media/Abilities/NOCOINFUD.png",
    effect: [],
},{
    title: "Network Effect",
    description: "Increases the effectiveness of all abilities.",
    thumbnail: 'src/Media/Abilities/NETWORKEFFECT.png',
    effect: [],
},
{
    title: "Chain Reaction",
    description: "Causes a chain reaction, revealing all enemies and drastically debuffing them while significantly buffing allies.",
    thumbnail: 'src/Media/Abilities/CHAINREACTION.png',
    effect: [],
},
{
    title: "FOMO Wave",
    description: "Induces fear of missing out, causing enemies to rush towards the player.",
    thumbnail: "src/Media/Abilities/FOMO.png",
    effect: [],
},
{
    title: "Chain Analysis",
    description: "Reveals hidden enemies and tracks their movements.",
    thumbnail: "src/Media/Abilities/ANALYSIS.png",
    effect: [],
},
{
    title: "Liquidation Wave",
    description: "Deals area-of-effect damage and reduces enemy defenses.",
    thumbnail: "src/Media/Abilities/MASSLIQUIDATION.png",
    effect: [],
},{
    title: "Quick Flip",
    description: "Deals instant damage to nearby enemies.",
    thumbnail: "src/Media/Abilities/QUICKFLIP.png",
    effect: [],
},
{
    title: "Dollar Cost average",
    description: "Deals Slow damage to nearby enemies.",
    thumbnail: "src/Media/Abilities/DCA.png",
    effect: [],
},
{
    title: "Jackpot",
    description: "Hits the jackpot, dealing massive damage to all enemies and providing significant buffs to allies.",
    thumbnail: "src/Media/Abilities/JACKPOT.png",
    effect: [],
},{
    title: "Airdrop",
    description: "Drops valuable items or buffs to allies.",
    thumbnail: 'src/Media/Abilities/AIRDROP.png',
    effect: [],
},
{
    title: "Blockchain Stress Test ",
    description: "Creates a zone where enemies take increased damage and have reduced speed.",
    thumbnail: 'src/Media/Abilities/STRESSTEST.png',
    effect: [],
},
{
    title: "Feature Test ",
    description: "Temporarily boosts allies' abilities.",
    thumbnail: 'src/Media/Abilities/FEATURETEST.png',
    effect: [],
},
{
    title: "Oracle Insight",
    description: "Predicts enemy movements, increasing evasion.",
    thumbnail: 'src/Media/Abilities/ORACLEINSIGHT.png',
    effect: [],
},
{
    title: "Whale Buy",
    description: "Unleashes a powerful area-of-effect attack, representing a large buy order.",
    thumbnail: "src/Media/Abilities/WHALEBUY.png",
    effect: [],
},
{
    title: " Trilemma Mastery",
    description: "Master the trilemma by providing significant buffs to attack, defense, and movement speed while weakening enemies.",
    thumbnail: "src/Media/Abilities/LAW.png",
    effect: [],
},
{
    title: "Oracle Manipulation",
    description: "Disrupts enemy abilities based on false data.",
    thumbnail: "src/Media/Abilities/ORACLEMANIPULATION.png",
    effect: [],
},
{
    title: "Market Manipulation ",
    description: "Temporarily controls enemy movements.",
    thumbnail: "src/Media/Abilities/MARKETMANIPULATION.png",
    effect: [],
},
{
    title: "Impermanent Loss",
    description: "Reduces damage taken from all sources.",
    thumbnail: 'src/Media/Abilities/IMPERMANENTLOSS.png',
    effect: [],
},
{
    title: "Tripool",
    description: "Creates three separate pools that buff allies' attack power.",
    thumbnail: 'src/Media/Abilities/TRIPOOL.png',
    effect: [],
},
{
    title: "Rug Pull",
    description: "Instantly removes buffs from enemies.",
    thumbnail: 'src/Media/Abilities/RUG.png',
    effect: [],
},
{
    title: "Debt Collector",
    description: "Focuses on sustained damage and debuffs.",
    thumbnail: "src/Media/Abilities/DEBTCOLLECTOR.png",
    effect: [],
},
{
    title: "Market Swing",
    description: "Temporarily increases critical hit chance and attack speed.",
    thumbnail: "src/Media/Abilities/MARKETSWING.png",
    effect: [],
},
{
    title: "Market Maker",
    description: "Balances the battlefield by adjusting enemy and ally stats.",
    thumbnail: 'src/Media/Abilities/MARKETMAKER.png',
    effect: [],
},
{
    title: "Two Pool",
    description: "Creates two separate pools that buff allies' attack speed.",
    thumbnail: 'src/Media/Abilities/TWOPOOL.png',
    effect: [],
},
{
    title: "Crypto Bridge",
    description: "Transfers resources between allies.",
    thumbnail: 'src/Media/Abilities/BRIDGE.png',
    effect: [],
},
{
    title: "Buyout Power",
    description: "Temporarily takes control of an enemy, turning them into an ally.",
    thumbnail: 'src/Media/Abilities/BUYPOWER.png',
    effect: [],
},
{
    title: "Merkle Proof",
    description: "Verifies resources securely.  preventing theft",
    thumbnail: 'src/Media/Abilities/MERKLE.png',
    effect: [],
},
{
    title: "Compliance Check",
    description: "Forces enemies to slow down and take damage over time.",
    thumbnail: 'src/Media/Abilities/COMPLIANCE.png',
    effect: [],
},
{
    title: "Crypto Portfolio",
    description: "Increases the efficiency of resource gathering.",
    thumbnail: 'src/Media/Abilities/FOLIO.png',
    effect: [],
},{
    title: "Zodiac Prediction ",
    description: "Predicts and reveals enemies' weaknesses, reducing their defenses.",
    thumbnail: 'src/Media/Abilities/ZODIAC.png',
    effect: [],
},
{
    title: "DeFi Yield",
    description: "Periodically grants a boost in resources.",
    thumbnail: 'src/Media/Abilities/DEFIYIELD.png',
    effect: [],
},
{
    title: 'Escrow Services',
    description: "Holds resources in escrow, releasing them after a delay.",
    thumbnail: 'src/Media/Abilities/ESCROW.png',
    effect: [],
},
{
    title: 'Bitcoin Dominance ',
    description: "Temporarily controls all enemies, making them fight each other.",
    thumbnail: 'src/Media/Abilities/DOMINANCE.png',
    effect: [],
},
{
    title: "NFT Disruptor",
    description: "Temporarily disables the effects of enemy NFTs.",
    thumbnail: 'src/Media/Abilities/NFTDISRUPTOR.png',
    effect: [],
},
{
    title: "Blockchain Analysis",
    description: "Provides insights to increase strategy effectiveness.",
    thumbnail: 'src/Media/Abilities/BLOCKANALYSIS.png',
    effect: [],
},
{
    title: "Decentralized Finance Expertise",
    description: "Increases the effectiveness of all resource-gathering abilities.",
    thumbnail: 'src/Media/Abilities/EXPERTISE.png',
    effect: [],
},
{
    title: "Trader's Instinct ",
    description: "Enhances movement speed and reduces skill cooldowns in critical moments.",
    thumbnail: 'src/Media/Abilities/INTUITION.png',
    effect: [],
},
{
    title: "Margin Call ",
    description: "Forces enemies to take damage over time.",
    thumbnail: 'src/Media/Abilities/MARGINCALL.png',
    effect: [],
},
{
    title: "Perfect Arbitrage",
    description: "Executes a perfect arbitrage, drastically increasing attack power and critical hit chance for a short period.",
    thumbnail: 'src/Media/Abilities/ARBITRAGE.png',
    effect: [],
},
{
    title: "Temperature Check",
    description: "Executes a perfect arbitrage, drastically increasing attack power and critical hit chance for a short period.",
    thumbnail: 'src/Media/Abilities/TEMPCHECK.png',
    effect: [],
},
{
    title: "Treasury Allocation",
    description: "Provides a large amount of resources to all allies.",
    thumbnail: 'src/Media/Abilities/TREASURYALLOC.png',
    effect: [],
},
{
    title: "Lucky Streak",
    description: "Temporarily increases critical hit chance and dodge rate.",
    thumbnail: 'src/Media/Abilities/STREAK.png',
    effect: [],
},
{
    title: "Self Custody",
    description: "Protects resources from being stolen.",
    thumbnail: 'src/Media/Abilities/CUSTODY.png',
    effect: [],
},
{
    title: "Flash Crash",
    description: "Briefly stuns all enemies in the area.",
    thumbnail: 'src/Media/Abilities/MARKETCRASH.png',
    effect: [],
},
{
    title: "Stake Defense",
    description: "Increases defense for a short period.",
    thumbnail: 'src/Media/Abilities/STAKEDEFENSE.png',
    effect: [],
},
 
{
    title: "Final Release",
    description: "Launches the final release, significantly buffing all allies and debuffing all enemies.",
    thumbnail: 'src/Media/Abilities/FINALRELEASE.png',
    effect: [],
},
{
    title: "Crypto Fork",
    description: "Creates a duplicate of an ability for a short time.",
    thumbnail: 'src/Media/Abilities/CRYPTOFORK.png',
    effect: [],
},
{
    title: "Crypto Wallet",
    description: "Stores resources securely.",
    thumbnail: 'src/Media/Abilities/WALLET.png',
    effect: [],
},
{
    title: "Slashing Protection",
    description: "Reduces damage taken from critical hits.",
    thumbnail: 'src/Media/Abilities/SLASHINGPROTECTION.png',
    effect: [],
},
{
    title: "Security Lockdown",
    description: "Reduces damage taken for a short period.",
    thumbnail: 'src/Media/Abilities/LOCKDOWN.png',
    effect: [],
},
{
    title: "Scalability Boost",
    description: "Increases attack speed and movement speed.",
    thumbnail: 'src/Media/Abilities/SCALABILITYBOOST.png',
    effect: [],
},

{
    title: "ICO Hype",
    description: "Temporarily boosts all stats.",
    thumbnail: 'src/Media/Abilities/ICOHYPE.png',
    effect: [],
},
{
    title: "ReBalancing ",
    description: "Spreads damage taken to nearby enemies.",
    thumbnail: 'src/Media/Abilities/REBALANCING.png',
    effect: [],
},
{
    title: "Crypto Rally",
    description: "Temporarily boosts all allies' speed.",
    thumbnail: 'src/Media/Abilities/RALLY.png',
    effect: [],
},
{
    title: "Crypto Whitelist",
    description: "Grants immunity to debuffs.",
    thumbnail: 'src/Media/Abilities/WHITELIST.png',
    effect: [],
},
{
    title: "Crypto Blacklist",
    description: "Grants immunity to buffs.",
    thumbnail: 'src/Media/Abilities/BLACKLIST.png',
    effect: [],
},
{
    title: "Pump and Dump",
    description: "Increases attack power significantly for a short duration, followed by a debuff.",
    thumbnail: 'src/Media/Abilities/PND.png',
    effect: [],
},
{
    title: "Pump",
    description: "Increases attack power significantly for a short duration",
    thumbnail: 'src/Media/Abilities/PUMP.png',
    effect: [],
},
{
    title: 'Lending Protocol',
    description: "Lends resources to allies temporarily.",
    thumbnail: 'src/Media/Abilities/LENDING.png',
    effect: [],
},
{
    title: 'Token Lock',
    description: "Locks an enemy's abilities temporarily.",
    thumbnail: 'src/Media/Abilities/TOKENLOCK.png',
    effect: [],
},
{
    title: "Locked In",
    description: "Maximize your profits and outpace the competition with unparalleled focus and strategic insight.",
    thumbnail: 'src/Media/Abilities/LOCKEDIN.png',
    effect: [],
},
{
    title: "Adaptive Trading",
    description: "Adapts to the situation, dealing damage based on the player's needs.",
    thumbnail: 'src/Media/Abilities/ADAPTIVETRADING.png',
    effect: [],
},
{
    title: "Token Burn",
    description: "Permanently removes a portion of enemy resources.",
    thumbnail: 'src/Media/Abilities/TOKENBURN.png',
    effect: [],
},
{
    title: "Delegation",
    description: "Allows the player to share buffs with allies.",
    thumbnail: 'src/Media/Abilities/DELEGATION.png',
    effect: [],
},
{
    title: "Protocol Mastery",
    description: "Master protocols to provide comprehensive buffs to all allies and debuff enemies significantly.",
    thumbnail: 'src/Media/Abilities/MASTERY.png',
    effect: [],
},
{
    title: "Protocol Exploit ",
    description: "Deals significant damage to a single target and restores health.",
    thumbnail: 'src/Media/Abilities/EXPLOIT.png',
    effect: [],
},
{
    title: "Protocol Patch",
    description: "Creates a temporary area that boosts allies' defenses.",
    thumbnail: 'src/Media/Abilities/PATCHDEPLOY.png',
    effect: [],
},
{
    title: "Inside Info",
    description: "Reveals hidden enemies and weak points.",
    thumbnail: 'src/Media/Abilities/INSIDEINFO.png',
    effect: [],
},
{
    title: "Debate",
    description: "Temporarily silences and weakens enemies.",
    thumbnail: 'src/Media/Abilities/DEBATE.png',
    effect: [],
},
{
    title: "Profit Taker ",
    description: "Buffs self and allies after defeating enemies.",
    thumbnail: 'src/Media/Abilities/PROFITTAKING.png',
    effect: [],
},
{
    title: "Regulatory Framework ",
    description: "Creates a barrier that blocks enemy movement.",
    thumbnail: 'src/Media/Abilities/REGULATORYFRAMEWORK.png',
    effect: [],
},
{
    title: "Transaction Revert",
    description: "Teleports the player to a previous location, avoiding damage.",
    thumbnail: 'src/Media/Abilities/TXREVERT.png',
    effect: [],
},
{
    title: "Code Review",
    description: "Temporarily reveals enemy weaknesses and increases damage dealt.",
    thumbnail: 'src/Media/Abilities/REVIEW.png',
    effect: [],
},
{
    title: "QA",
    description: "Enhances ally buffs and reduces enemy effectiveness.",
    thumbnail: 'src/Media/Abilities/QUALITYASSURANCE.png',
    effect: [],
},
{
    title: "Let him Cook",
    description: "Over time, gains stats exponentially.",
    thumbnail: 'src/Media/Abilities/COOK.png',
    effect: [],
},

{
    title: 'Token UnLock',
    description: "Locks an enemy's abilities temporarily.",
    thumbnail: 'src/Media/Abilities/TOKENUNLOCK.png',
    effect: [],
},
{
    title: "Crop Rotation",
    description: "Switches between different buffs to suit the player's needs.",
    thumbnail: 'src/Media/Abilities/ROTATION.png',
    effect: [],
},
{
    title: "Crypto Dapp",
    description: "Creates a decentralized application for resource generation.",
    thumbnail: 'src/Media/Abilities/DAPP.png',
    effect: [],
},
{
    title: "Crypto Bounty",
    description: "Rewards for defeating enemies.",
    thumbnail: 'src/Media/Abilities/CRYPTOBOUNTY.png',
    effect: [],
},
{
    title: "Liquidity Vampire",
    description: "Steals resources and buffs self and allies.",
    thumbnail: "src/Media/Abilities/LIQUIDITYVAMPIRE.png",
    effect: [],
},
{
    title: "Malware Injection ",
    description: "Inflicts damage over time and reduces enemy attack speed.",
    thumbnail: "src/Media/Abilities/BUG.png",
    effect: [],
},
{
    title:  "Network Consensus",
    description: "Achieves network consensus, significantly boosting allies' defense and providing damage immunity for a short period.",
    thumbnail: "src/Media/Abilities/CONSENSUS.png",
    effect: [],
},
{
    title: "Chain Split",
    description: "Creates a duplicate of yourself to confuse enemies.",
    thumbnail: 'src/Media/Abilities/CHAINSPLIT.png',
    effect: [],
},
{
    title: "Validator Uptime",
    description: "Increases the duration of all buffs.",
    thumbnail: 'src/Media/Abilities/VALIDATORUPTIME.png',
    effect: [],
},
{
    title: "Exit Scam",
    description: "Teleports to a safe location and leaves a damaging decoy behind.",
    thumbnail: 'src/Media/Abilities/EXITSCAM.png',
    effect: [],
},
{
    title: "Sellout",
    description: "Trades a portion of your resources for a temporary power boost.",
    thumbnail: 'src/Media/Abilities/SELLOUT.png',
    effect: [],
},
{
    title: "Protocol Crash",
    description: "Creates a zone where enemies take increased damage and have reduced speed.",
    thumbnail: 'src/Media/Abilities/PROTOCOLCRASH.png',
    effect: [],
},
{
    title: "Trading Frenzy",
    description: "Increases speed and critical hit chance drastically for a short time.",
    thumbnail: 'src/Media/Abilities/TRADINGFRENZY.png',
    effect: [],
},
{
    title: "Hash Power",
    description: "Temporarily increases attack power.",
    thumbnail: 'src/Media/Abilities/HASHPOWER.png',
    effect: [],
},
{
    title: "Miner Network",
    description: "Creates a zone that damages enemies over time.",
    thumbnail: 'src/Media/Abilities/MINERNETWORK.png',
    effect: [],
},
{
    title: "Validator Support",
    description: "Summons a temporary ally to aid in battle.",
    thumbnail: 'src/Media/Abilities/VALIDATORSUPPORT.png',
    effect: [],
},
{
    title: "Diamond Hands ",
    description: "Reduces damage taken significantly for a short period.",
    thumbnail: 'src/Media/Abilities/DIAMONDHANDS.png',
    effect: [],
},
{
    title: "HODL",
    description: "Increases the player's defense.",
    thumbnail: 'src/Media/Abilities/HODL.png',
    effect: [],
},
{
    title: "Titanium Support ",
    description: "Creates a barrier that absorbs damage.",
    thumbnail: 'src/Media/Abilities/SUPPORT.png',
    effect: [],
},
{
    title: 'The Citadel',
    description: "Constructs a powerful fortress that provides extensive protection to allies and significantly disrupts enemies.",
    thumbnail: 'src/Media/Abilities/CITADEL.png',
    effect: [],
},
{
    title: "Total Shutdown",
    description: "Shuts down all enemy abilities and greatly reduces their stats for a short period.",
    thumbnail: 'src/Media/Abilities/SHUTDOWN.png',
    effect: [],
},
{
    title: 'Market Stabilization',
    description: "Stabilizes prices, reducing enemy attack power and increasing ally defense.",
    thumbnail: 'src/Media/Abilities/STABILIZATION.png',
    effect: [],
},
{
    title: "Contract Breach",
    description: "Disables enemy abilities for a short period.",
    thumbnail: 'src/Media/Abilities/BREACH.png',
    effect: [],
},
{
    title: "Single Stake",
    description: "Increases health regeneration based on a single stake.",
    thumbnail: 'src/Media/Abilities/SINGLESTAKE.png',
    effect: [],
},
{
    title: "Capital Injection ",
    description: "Provides a significant health boost to the player or an ally.",
    thumbnail: 'src/Media/Abilities/CAPITALINJECTION.png',
    effect: [],
},
{
    title: "Due Diligence",
    description: "Reveals enemies' weaknesses and reduces their defenses.",
    thumbnail: 'src/Media/Abilities/DD.png',
    effect: [],
},
{
    title: "Funding Boost ",
    description: "Increases resource generation for a short period.",
    thumbnail: 'src/Media/Abilities/FUNDINGBOOST.png',
    effect: [],
},
{
    title: "Firewall Fort",
    description: "Increases the player's defense temporarily.",
    thumbnail: 'src/Media/Abilities/FIREWALL.png',
    effect: [],
},
{
    title: "DeFi Supremacy",
    description: "Establishes complete DeFi dominance, significantly enhancing all aspects of resource generation and providing massive buffs to allies.",
    thumbnail: 'src/Media/Abilities/DEFISUPREMACY.png',
    effect: [],
},
{
    title: "Leveraged Yield",
    description: "Increases resource generation for a short period.",
    thumbnail: 'src/Media/Abilities/LEVERAGEDYIELD.png',
    effect: [],
},
{
    title: "Collector Frenzy",
    description: "Calls upon devoted collectors to swarm enemies, dealing massive damage.",
    thumbnail: 'src/Media/Abilities/COLLECTORSFRENZY.png',
    effect: [],
},
{
    title: 'Capitulation',
    description: "Spreads widespread fear and panic, causing enemies to lose resources and morale.",
    thumbnail: 'src/Media/Abilities/CAPITULATION.png',
    effect: [],
},
{
    title: "Maxi Ascendancy",
    description: "Ascends to a state of maximum power, drastically increasing all stats and providing powerful buffs to allies for a short period.",
    thumbnail: 'src/Media/Abilities/MAXIAS.png',
    effect: [],
},
{
    title: "Inspection",
    description: "Reveals and debuffs all enemies in a targeted area.",
    thumbnail: 'src/Media/Abilities/INSPECTION.png',
    effect: [],
},
{
    title: "Exit Hatch ",
    description: "Grants one extra life.",
    thumbnail: 'src/Media/Abilities/EXITHATCH.png',
    effect: [],
},
{
    title: "Chain Reorg",
    description: "Rewinds time slightly to undo recent events.",
    thumbnail: 'src/Media/Abilities/CHAINREORG.png',
    effect: [],
},
{
    title: "Pact with the Devil",
    description: "Grants a significant boost in power at the cost of health.",
    thumbnail: 'src/Media/Abilities/PACTWITHTHEDEVIL.png',
    effect: [],
},
{
    title: "Congestion",
    description: "Slows all enemies for a short duration.",
    thumbnail: "src/Media/Abilities/CONGESTION.png",
    effect: [],
},
{
    title: "Mining Frenzy",
    description: "Triggers a mining frenzy, drastically increasing attack power and speed for a short period.",
    thumbnail: "src/Media/Abilities/MININGFRENZY.PNG",
    effect: [],
},
{
    title: "DDoS Attack",
    description: "Stuns all enemies for a short duration.",
    thumbnail: "src/Media/Abilities/DDOS.png",
    effect: [],
},
{
    title: "Interest Yield",
    description: "Gradually regenerates health over time.",
    thumbnail: 'src/Media/Abilities/INTERESTYIELD.png',
    effect: [],
},
{
    title: "Monolithic Design",
    description: "Provides a significant health boost.",
    thumbnail: 'src/Media/Abilities/MONOLITHICDESIGN.png',
    effect: [],
},
{
    title: "Multilayer Design",
    description: "Adds an additional layer of defense.",
    thumbnail: 'src/Media/Abilities/MULTILAYERDESIGN.png',
    effect: [],
},
{
    title: "Layer 2 Scaling",
    description: "Reduces the cost and cooldown of all abilities.",
    thumbnail: 'src/Media/Abilities/LAYERSCALING.png',
    effect: [],
},
{
    title: "Market Patience",
    description: "Gradually regenerates health over time.",
    thumbnail: 'src/Media/Abilities/PATIENCE.png',
    effect: [],
},
{
    title: "Liquidity Mining",
    description: "Generates resources over time.",
    thumbnail: 'src/Media/Abilities/LIQUIDITYMINING.png',
    effect: [],
},
{
    title: "Gas Optimization",
    description: "Decreases mana cost of all abilities.",
    thumbnail: 'src/Media/Abilities/GASOPTIMIZATION.png',
    effect: [],
},
{
    title: "Bearish Sentiment",
    description: "Reduces enemies' attack power.",
    thumbnail: 'src/Media/Abilities/BEARISHSENTIMENT.png',
    effect: [],
},
{
    title: "Whale Games",
    description: "Uses overwhelming power to crush enemies.",
    thumbnail: 'src/Media/Abilities/CRYPTOWHALE.png',
    effect: [],
},
{
    title: "Bullish Sentiment",
    description: "Increases allies' attack power.",
    thumbnail: 'src/Media/Abilities/BULLISHSENTIMENT.png',
    effect: [],
},
{
    title: "Vampire ATTACK",
    description: "Steals resources.",
    thumbnail: "src/Media/Abilities/VAMPIREATTACK.png",
    effect: [],
},
{
    title: "Black Swan Event",
    description: "Creates a chaotic event that massively disrupts enemy abilities and resources while providing significant buffs to allies.",
    thumbnail: "src/Media/Abilities/BLACKSWAM.png",
    effect: [],
},
{
    title: "Dead Cat Bounce",
    description: "Temporarily makes the player invincible and greatly increases attack power.",
    thumbnail: 'src/Media/Abilities/DEADCATBOUNCE.png',
    effect: [],
},
{
    title: "White Swan Event",
    description: "Creates an event that massively benefits all market participants providing significant buffs.",
    thumbnail: "src/Media/Abilities/WHITESWAM.png",
    effect: [],
},
{
    title: "Crab Market Action ",
    description: "Reverses buff and debuffs of everyone for the rest of the game .",
    thumbnail: "src/Media/Abilities/CRABACTION.png",
    effect: [],
},
{
    title: 'Unicorn Startup',
    description: 'a very rare sight.',
    thumbnail: 'src/Media/Abilities/UNICORN.png',
    effect: [],
},
{
    title: "Male Astrology",
    description: "Predicts and reveals enemies' weaknesses, reducing their defenses.",
    thumbnail: 'src/Media/Abilities/ASTROLOGY.png',
    effect: [],
},
{
    title: "NFT Enhancer",
    description: "Boosts the effects of your NFTs.",
    thumbnail: 'src/Media/Abilities/NFTREWORK.png',
    effect: [],
},

{
    title: "Debt Drown ",
    description: "Provides a temporary boost to defense and health regeneration.",
    thumbnail: 'src/Media/Abilities/DEBTDROWN.png',
    effect: [],
},
{
    title: "NFT Marketplace",
    description: "Increases the drop rate of rare items.",
    thumbnail: 'src/Media/Abilities/NFTMARKET.png',
    effect: [],
},
{
    title: "Sanction",
    description: "Targets a single enemy, greatly reducing its speed and defense.",
    thumbnail: 'src/Media/Abilities/SANCTION.png',
    effect: [],
},
{
    title: "Scam Alert ",
    description: "Temporarily decreases enemies' attack power and movement speed.",
    thumbnail: 'src/Media/Abilities/SCAM.png',
    effect: [],
},

{
    title: "Double or Nothing ",
    description: "Randomly buffs or debuffs the player.",
    thumbnail: 'src/Media/Abilities/DOUBLEORNOTHING.png',
    effect: [],
},
{
    title: "Skeptical Scholar",
    description: "Buffs allies' defense and reduces enemy effectiveness.",
    thumbnail: 'src/Media/Abilities/SKEPTIC.png',
    effect: [],
},
{
    title: 'Policy Overhaul',
    description: "Executes a policy overhaul, providing massive buffs to allies and drastically debuffing enemies across the battlefield.",
    thumbnail: 'src/Media/Abilities/OVERHAUL.png',
    effect: [],
},

{
    title: "Lunar Cycle ",
    description: "Provides buffs or debuffs based on the current moon phase.",
    thumbnail: 'src/Media/Abilities/LUNARCYCLE.png',
    effect: [],
},
{
    title: "Crypto Signal",
    description: "Calls for reinforcements to aid in battle.",
    thumbnail: 'src/Media/Abilities/CRYPTOSIGNAL.png',
    effect: [],
},
{
    title: "Flash Loan",
    description: "Temporarily boosts resources for a short period.",
    thumbnail: 'src/Media/Abilities/FLASHLOAN.png',
    effect: [],
},
{
    title: "Star Alignment ",
    description: "Increases critical hit chance and attack power when stars align.",
    thumbnail: 'src/Media/Abilities/ALIGNMENT.png',
    effect: [],
},
{
    title: "Risk Taker",
    description: "High-risk, high-reward abilities.",
    thumbnail: 'src/Media/Abilities/RISKTAKER.png',
    effect: [],
},
{
    title: "Shill",
    description: "Temporarily increases allies' attack power and speed.",
    thumbnail: 'src/Media/Abilities/SHILLING.png',
    effect: [],
},
{
    title: "Compound Interest ",
    description: "Gradually increases attack power and defense over time.",
    thumbnail: 'src/Media/Abilities/COMPOUND.png',
    effect: [],
},
{
    title: "Hype Train",
    description: "Summons a stampede of followers that trample enemies.",
    thumbnail: 'src/Media/Abilities/HYPETRAIN.png',
    effect: [],
},
{
    title: "Virality ",
    description: "Goes viral, drastically increasing the effectiveness of all abilities and summoning followers to fight alongside.",
    thumbnail: 'src/Media/Abilities/VIRALITY.png',
    effect: [],
},
{
    title: "Viral Spread ",
    description: "Goes viral, drastically increasing the effectiveness of all abilities and summoning followers to fight alongside.",
    thumbnail: 'src/Media/Abilities/SPREAD.png',
    effect: [],
},
{
    title: "Second Best ",
    description: "Gradually increases attack power and defense over time.",
    thumbnail: 'src/Media/Abilities/SECONDBEST.png',
    effect: [],
},
{
    title: "Martket Impact",
    description: "Enhances debuffs and controls enemy behavior.",
    thumbnail: 'src/Media/Abilities/MARKETIMPACT.png',
    effect: [],
},
{
    title: "It's Over ",
    description: "over.",
    thumbnail: 'src/Media/Abilities/OVER.png',
    effect: [],
},
{
    title: "All In",
    description: "Deals massive damage to a single target but leaves the player vulnerable.",
    thumbnail: 'src/Media/Abilities/ALLIN.png',
    effect: [],
},
{
    title: "Token Swap",
    description: "Exchanges debuffs for buffs with enemies.",
    thumbnail: 'src/Media/Abilities/COINSWAP.png',
    effect: [],
},
{
    title: 'Bug Fixing',
    description: "Fixes bugs in the code, restoring a small amount of health.",
    thumbnail: 'src/Media/Abilities/ASSISTEDBUGFIXING.png',
    effect: [],
},
{
    title: 'Upgrade Shiping',
    description: "Splits the player's attacks into multiple projectiles, hitting more enemies.",
    thumbnail: 'src/Media/Abilities/SHIPPING.png',
    effect: [],
},
{
    title: "Protocol Raider",
    description: "Focuses on high-damage, single-target attacks.",
    thumbnail: 'src/Media/Abilities/RAIDING.png',
    effect: [],
},

{
    title: "Sidechains",
    description: "Allows the player to create decoys that distract enemies.",
    thumbnail: "src/Media/Abilities/SIDECHAIN.png",
    effect: [],
},
{
    title: "Gas Limit",
    description: "Reduces the speed of all enemies in a large area.",
    thumbnail: "src/Media/Abilities/GASLIMIT.png",
    effect: [],
},
{
    title: "Critical Patch",
    description: "Deploys a critical patch, significantly buffing all allies and debuffing all enemies.",
    thumbnail: "src/Media/Abilities/CRITICALPATCH.png",
    effect: [],
},
{
    title: 'Light Node Run',
    description: "Increases movement speed.",
    thumbnail: "src/Media/Abilities/LNRUN.png",
    effect: [],
},
{
    title: "Crypto Investigation",
    description: "Buffs self and allies based on revealed enemy locations.",
    thumbnail: "src/Media/Abilities/CRYPTOINVESTIGATION.png",
    effect: [],
},
{
    title: "Criminal Hunt ",
    description: "Deals extra damage to recently revealed enemies.",
    thumbnail: "src/Media/Abilities/CRIMINALHUNT.png",
    effect: [],
},
{
    title: "Transaction Trace",
    description: "Temporarily reduces enemy speed and reveals weak points.",
    thumbnail: "src/Media/Abilities/TXTRACE.png",
    effect: [],
},
{
    title: "Protocol Drain",
    description: "Drains multiple protocols simultaneously, dealing massive damage to all enemies and providing significant resources to allies.",
    thumbnail: "src/Media/Abilities/DRAIN.png",
    effect: [],
},
{
    title: "NFT Masterpiece",
    description: "Creates a stunning piece of digital art that distracts enemies and boosts allies' morale.",
    thumbnail: "src/Media/Abilities/NFTMASTERPIECE.png",
    effect: [],
},
{
    title: "Whale Alert",
    description: "Marks the strongest enemy, increasing damage dealt to them",
    thumbnail: "src/Media/Abilities/WHALEALERT.png",
    effect: [],
},
{
    title: "Smart Contract Deployment",
    description: "Deploys a smart contract to trap and damage enemies.",
    thumbnail: 'src/Media/Abilities/SMARTCONTRACT.png',
    effect: [],
},
{
    title: "Smart Contract Audit",
    description: "Identifies and negates enemy traps.",
    thumbnail: 'src/Media/Abilities/SMARTCONTRACTAUDIT.png',
    effect: [],
},
{
    title: "Smart Contract Hack",
    description: "Deals consistent damage over time to enemies.",
    thumbnail: 'src/Media/Abilities/SMARTCONTRACTHACK.png',
    effect: [],
},
{
    title: "Quantum Key Exchange 🔑",
    description: "Transfers health from enemies to the player.",
    thumbnail: 'src/Media/Abilities/QKEYEX.png',
    effect: [],
},
{
    title: "Bot Armada",
    description: "Summons an entire armada of bots for massive support and damage.",
    thumbnail: 'src/Media/Abilities/ARMADA.png',
    effect: [],
},
{
    title: "MEV Bot",
    description: "Drains health from enemies based on their movements.",
    thumbnail: 'src/Media/Abilities/MEVBOT.png',
    effect: [],
},
{
    title: "Fear Spread",
    description: "Spreads fear, causing enemies to flee in random directions.",
    thumbnail: 'src/Media/Abilities/FEAR.png',
    effect: [],
},
{
    title: "FUD Storm",
    description: "Creates confusion among enemies, reducing their effectiveness.",
    thumbnail: 'src/Media/Abilities/FUDSTORM.png',
    effect: [],
},
{
    title: "White Paper",
    description: "Grants temporary immunity to damage.",
    thumbnail: 'src/Media/Abilities/WHITEPAPER.png',
    effect: [],
},
{
    title: "Yellow Paper",
    description: "Grants temporary immunity to damage.",
    thumbnail: 'src/Media/Abilities/YELLOWPAPER.png',
    effect: [],
},


];

*/