export const playerTypes = [{
    title: 'Onchain Survivor',
    description:'The jack of all traders, after losing it all in the 2018 bear market he decided to stay around and keep trying.',
    thumbnail: 'Media/Classes/Onchain Survivor/MSURVIVOR.png',
    abilities:[],
},{
    title: 'Onchain Survivor',
    description: 'This Character Bio has not been discovered',    
    thumbnail: 'Media/Classes/Onchain Survivor/FSURVIVOR.png',
    abilities: [],
},{    
    title: 'Miner',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Miner/MMINER.png',
    abilities: [],
},{    
    title: 'Miner',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Miner/FMINER.png',
    abilities: [],
},{
    title: 'Staker',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Staker/MSTAKER.png',
    abilities: [],  
},{
    title: 'Staker',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Staker/FSTAKER.png',
    abilities: [], 
},{
    title: 'Developer',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Developer/MDEVELOPER.png',
    abilities: [],
},{
    title: 'Developer',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Developer/FDEVELOPER.png',
    abilities: [],
},{
    title: 'Trader',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Trader/MTRADER.png',
    abilities: [],
},{
    title: 'Trader',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Trader/FTRADER.png',
    abilities: [],
},{
    title: 'Regulator',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Regulator/MREGULATOR.png',
    abilities: [],
},{
    title: 'Regulator',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Regulator/FREGULATOR.png',
    abilities: [],
},{
    title: 'Quantum Cryptographer',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Quantum/MQUANTUM.png',
    abilities: [],
},{
    title: 'Quantum Cryptographer',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Quantum/FQUANTUM.png',
    abilities: [],
},{
    title: 'Crypto Botter',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Crypto Botter/MBOTTER.png',
    abilities: [],
},{
    title: 'Crypto Botter',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Crypto Botter/FBOTTER.png',
    abilities: [],
},{
    title: 'Fudder',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Fudder/MFUDDER.png',
    abilities: [],
},{
    title: 'Fudder',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Fudder/FFUDDER.png',
    abilities: [],
},
{
    title: 'Crypto Astrologer',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Astrologer/MASTROLOGER.png',
    abilities: [],
},
{
    title: 'Crypto Astrologer',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Astrologer/FASTROLOGER.png',
    abilities: [],
},
{
    title: 'Influencer',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Influencer/MINFLUENCER.jpg',
    abilities: [],
},
{
    title: 'Influencer',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Influencer/FINFLUENCER.png',
    abilities: [],
},{
    title: 'Cabal Insider',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Insider Cabal/MCABAL.png',
    abilities: [],
},{
    title: 'Cabal Insider',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Insider Cabal/FCABAL.png',
    abilities: [],
},{
    title: 'Bitcoin MAXI',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Maxi/MMAXI.png',
    abilities: [],
},{
    title: 'Bitcoin MAXI',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Maxi/FMAXI.png',
    abilities: [],
},{
    title: 'Gambler',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Gambler/MGAMBLER.png',
    abilities: [],
},{
    title: 'Gambler',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Gambler/FGAMBLER.png',
    abilities: [],
},{
    title: 'Liquidator',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Liquidator/MLIQUIDATOR.png',
    abilities: [],
},{
    title: 'Liquidator',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Liquidator/FLIQUIDATOR.png',
    abilities: [], 
},{
    title: 'Nocoiner',
    description:  'This Character Bio has not been discovered',

    thumbnail: 'Media/Classes/Nocoiner/MNOCOINER.png',
    abilities: [],

},{
    title: 'Nocoiner',
    description:  'This Character Bio has not been discovered',

    thumbnail: 'Media/Classes/Nocoiner/FNOCOINER.png',
    abilities: [],

},{
    title: 'Auditor',
    description:  'This Character Bio has not been discovered',

    thumbnail: 'Media/Classes/Auditor/MAUDITOR.png',
    abilities: [],

},{
    title: 'Auditor',
    description:  'This Character Bio has not been discovered',

    thumbnail: 'Media/Classes/Auditor/FAUDITOR.png',
    abilities: [],

},{
    title: 'Sleuth',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Sleuth/MSLEUTH.png',
    abilities: [], 
},{
    title: 'Sleuth',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Sleuth/FSLEUTH.png',
    abilities: [], 
},{
    title: 'Beta Tester',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Beta Tester/MBETATESTER.png',
    abilities: [],
},{
    title: 'Beta Tester',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Beta Tester/FBETATESTER.png',
    abilities: [],
},{
    title: 'Defi Expert',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Defi/MDEFI.png',
    abilities: [],
},{
    title: 'Defi Expert',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Defi/FDEFI.png',
    abilities: [],
},{
    title: 'Defi Hacker',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Defi Hacker/MDEFIHACKER.png',
    abilities: [],
},{
    title: 'Defi Hacker',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Defi Hacker/FDEFIHACKER.png',
    abilities: [],
},{
    title: 'Sybiller',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Sybiller/MSYBILLER.png',
    abilities: [],
},{
    title: 'Sybiller',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Sybiller/FSYBILLER.png',
    abilities: [],
},
{
    title: 'Validator',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Validator/MVALIDATOR.png',
    abilities: [],
},
{
    title: 'Validator',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Validator/FVALIDATOR.jpg',
    abilities: [],
},{
    title: 'Industrial Miner',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Industrial Miner/MINDUSTRIAL.png',
    abilities: [],
},
{
    title: 'Industrial Miner',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Industrial Miner/FINDUSTRIAL.png',
    abilities: [],
},{
    title: 'High Frequency Trader',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/HFT/MHFT.png',
    abilities: [],
},
{
    title: 'High Frequency Trader',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/HFT/FHFT.png',
    abilities: [],
},{
    title: 'Liquid Staker',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Liquid/MLIQUID.png',
    abilities: [],
},{
    title: 'Liquid Staker',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Liquid/FLIQUID.png',
    abilities: [],
},{
    title: 'Dormant Holder',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Dormant Holder/MDORMANT.png',
    abilities: [],
},
{
    title: 'Dormant Holder',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Dormant Holder/FDORMANT.png',
    abilities: [],
},{
    title: 'Solo Node Runner',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Solo Node Runner/MSOLONODERUNNER.png',
    abilities: [],
},
{
    title: 'Solo Node Runner',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Solo Node Runner/FSOLONODERUNNER.png',
    abilities: [],
},
{
    title: 'Sniper',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Sniper/MSNIPER.png',
    abilities: [], 
},
{
    title: 'Sniper',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Sniper/FSNIPER.png',
    abilities: [], 
},
{
    title: 'Governance Staker',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Governance Staker/MGOV.jpg',
    abilities: [],
},{
    title: 'Governance Staker',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Governance Staker/FGOV.png',
    abilities: [],
},{
    title: 'Yield Farmer',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Farmer/MFARMER.png',
    abilities: [], 
},{
    title: 'Yield Farmer',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Farmer/FFARMER.png',
    abilities: [], 
},
{
    title: 'Venture Capital',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Venture Capital/MVC.png',
    abilities: [],
},{
    title: 'Venture Capital',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Venture Capital/FVC.png',
    abilities: [],
},{
    title: 'Decentralization Trillemma Solver',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Trillemma Solver/MSOLVER.jpg',
    abilities: [],
},{
    title: 'Decentralization Trillemma Solver',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Trillemma Solver/FSOLVER.png',
    abilities: [],
},{
    title: 'Tether Truther',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/TRUTHER/MTRUTHER.png',
    abilities: [],
},{
    title: 'Tether Truther',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/TRUTHER/FTRUTHER.png',
    abilities: [],
},{
    title: 'Mercerany Capital',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Mercenary Capital/MMERCENARY.png',
    abilities: [],
},{
    title: 'Mercerany Capital',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Mercenary Capital/FMERCENARY.png',
    abilities: [],
},{
    title: 'Copy Trader',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Copy Trader/MCOPYTRADER.png',
    abilities: [],
},{
    title: 'Copy Trader',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Copy Trader/FCOPYTRADER.png',
    abilities: [],
},{
    title: 'Policy Maker',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Policy Maker/MPOLICYMAKER.png',
    abilities: [],
},{
    title: 'Policy Maker',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Policy Maker/FPOLICYMAKER.png',
    abilities: [],
},{
    title: 'Angel Investor',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Angel/MANGEL.png',
    abilities: [],
},{
    title: 'Angel Investor',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Angel/FANGEL.png',
    abilities: [],
},
{
    title: 'Holder',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Holder/MHOLDER.png',
    abilities: [],
},
{
    title: 'Holder',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Holder/FHOLDER.png',
    abilities: [],
},
{
    title: 'C.E.X. C.E.O.',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/CEX/MCEX.png',
    abilities: [],
},
{
    title: 'C.E.X. C.E.O.',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/CEX/FCEX.png',
    abilities: [],
},
{
    title: 'USD Maxi',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/USD Maxi/MUSDMAXI.png',
    abilities: [],
},
{
    title: 'USD Maxi',
    description:  'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/USD Maxi/FUSDMAXI.png',
    abilities: [],
},
{
    title: 'Market Maker',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Market Maker/MMARKETMAKER.png',
    abilities: [],
},
{
    title: 'Market Maker',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Market Maker/FMARKETMAKER.png',
    abilities: [],
},
{
    title: 'Wallet Maker',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Wallet Maker/MWALLETMAKER.png',
    abilities: [],
},
{
    title: 'Wallet Maker',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Wallet Maker/FWALLETMAKER.png',
    abilities: [],
},
{
    title: 'Oracle',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Oracle/MORACLE.jpg',
    abilities: [],
},
{
    title: 'Oracle',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Oracle/FORACLE.png',
    abilities: [],
},
{
    title: 'Whale',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Whale/MWHALE.png',
    abilities: [], 
},
{
    title: 'Whale',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Whale/FWHALE.png',
    abilities: [],
},
{
    title: 'Shrimp',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Shrimp/MSHRIMP.png',
    abilities: [],
},
{
    title: 'Shrimp',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Shrimp/FSHRIMP.png',
    abilities: [],
},
{
    title: 'LARP',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/LARP/MLARP.png',
    abilities: [],
},
{
    title: 'LARP',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/LARP/FLARP.png',
    abilities: [],
},
{
    title: 'Grifter',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Grifter/MGRIFTER.png',
    abilities: [],
},
{
    title: 'Grifter',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Grifter/FGRIFTER.png',
    abilities: [],
},
{
    title: 'NFT Artist',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/NFT Artist/MNFTARTIST.png',
    abilities: [],
},
{
    title: 'NFT Artist',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/NFT Artist/FNFTARTIST.png',
    abilities: [],
},
{
    title: 'NFT Collector',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/NFT Collector/MNFTCOLLECTOR.png',
    abilities: [],

},
{
    title: 'NFT Collector',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/NFT Collector/FNFTCOLLECTOR.png',
    abilities: [],
},
{
    title: 'CTO Leader',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/CTO Leader/MCTOLEADER.png',
    abilities: [],
},
{
    title: 'CTO Leader',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/CTO Leader/FCTOLEADER.png',
    abilities: [],
},
{
    title: 'Serial Scammer',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Serial Scammer/MSERIALSCAMMER.png',
    abilities: [],
},
{
    title: 'Serial Scammer',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Serial Scammer/FSERIALSCAMMER.png',
    abilities: [],
},{
    title: 'Bagholder',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Bagholder/MBAGHOLDER.png',
    abilities: [], 
},{
    title: 'Bagholder',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Bagholder/FBAGHOLDER.png',
    abilities: [], 
},{
    title: 'Community Member',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Community Member/MCOMMUNITYMEMBER.png',
    abilities: [], 
},{
    title: 'Community Member',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Community Member/FCOMMUNITYMEMBER.png',
    abilities: [], 
},
{
    title: 'ICO Pioneer',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Pioneer/MPIONEER.png',
    abilities: [],
},
{
    title: 'ICO Pioneer',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Pioneer/FPIONEER.png',
    abilities: [],
},
{
    title: 'Defi Native',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Defi Native/MDEFINATIVE.png',
    abilities: [],
},
{
    title: 'Defi Native',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Defi Native/FDEFINATIVE.png',
    abilities: [],
},
{
    title: 'Metaverse Landowner',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Metaverse Landowner/MMETAVERSELANDOWNER.png',
    abilities: [],
},
{
    title: 'Metaverse Landowner',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Metaverse Landowner/FMETAVERSELANDOWNER.png',
    abilities: [],
},

{
    title: 'MEVil Genius',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Evil Genius/MEVILGENIUS.png',
    abilities: [],
},
{
    title: 'MEVil Genius',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Evil Genius/FEVILGENIUS.png',
    abilities: [],
},
{
    title: 'Ponzi Designer',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Ponzi Designer/MPONZIDESIGNER.png',
    abilities: [],
},
{
    title: 'Ponzi Designer',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Ponzi Designer/FPONZIDESIGNER.png',
    abilities: [],
},
{
    title: 'Caller',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Caller/MCALLER.png',
    abilities: [],
},
{
    title: 'Caller',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Caller/FCALLER.png',
    abilities: [],
},
{
    title: 'Backstabber',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Backstabber/MBACKSTABBER.png',
    abilities: [],
},
{
    title: 'Backstabber',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Backstabber/FBACKSTABBER.png',
    abilities: [],
},
{
    title: 'Trencher',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Trencher/MTRENCHER.png',
    abilities: [],
},
{
    title: 'Trencher',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Trencher/FTRENCHER.png',
    abilities: [],
},
{
    title: 'Beggar',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Beggar/MBEGGAR.png',
    abilities: [],
},
{
    title: 'Beggar',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Beggar/FBEGGAR.png',
    abilities: [], 
},
{
    title: 'Protagonist',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Protagonist/MPROTAG.png',
    abilities: [], 
},
{
    title: 'Protagonist',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Protagonist/FPROTAG.png',
    abilities: [], 
},
{
    title: 'Intern',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Intern/MINTERN.png',
    abilities: [], 
},
{
    title: 'Intern',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Intern/FINTERN.png',
    abilities: [], 
},
{
    title: 'Mod',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Mod/MMOD.png',
    abilities: [],
},
{
    title: 'Mod',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Mod/FMOD.png',
    abilities: [],
},{
    title: 'Seedless Survivor',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Seedless/MSEEDLESS.png',
    abilities: [],
},{
    title: 'Seedless Survivor',
    description: 'This Character Bio has not been discovered',
    thumbnail: 'Media/Classes/Seedless/FSEEDLESS.png',
    abilities: [],
},];